{
  "subject": "process",
  "action": "read",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "4",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.runningboardd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_access_resource",
  "importance": "info",
  "msgid": "55",
  "object.path": "/usr/libexec",
  "subject.account.id": "0",
  "subject.account.session_id": "195",
  "subject.process.fullpath": "/usr/libexec/runningboardd",
  "subject.process.hash": "UNKNOWN:09A000C17AB15DB74100C7A6C9AEEA56BF8E904F",
  "subject.process.id": "195",
  "subject.process.name": "runningboardd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T12:01:31.306Z"
}