{
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "1546889070",
  "datafield1": "exe",
  "datafield2": "root",
  "datafield3": "0755",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.107",
  "event_src.rule": "pt_siem_api_xattr",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "lsetxattr",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/usr/bin/newuidmap",
  "object.id": "3970416",
  "object.name": "newuidmap",
  "object.path": "/usr/bin/",
  "object.property": "extended_attributes",
  "object.type": "executable_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/bin/dockerd",
  "subject.process.id": "1757446",
  "subject.process.meta": "docker-untar / /var/lib/docker/overlay2/2bfca9c31aa03398db6466998043612c04760a26dc34d2acd5ddfcc81cea26a8/diff",
  "subject.process.name": "dockerd",
  "subject.process.parent.id": "1542",
  "subject.process.path": "/usr/bin/",
  "time": "2022-05-24T14:13:59.000Z"
}