{
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "14051591",
  "datafield1": "cp",
  "datafield2": "systemd-timesync",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.176.183",
  "event_src.rule": "pt_siem_api_xattr",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "fsetxattr",
  "numfield2": 100,
  "object.account.group": "nogroup",
  "object.account.id": "100",
  "object.account.name": "systemd-timesync",
  "object.id": "128675020",
  "object.property": "extended_attributes",
  "object.type": "regular_file",
  "subject.account.id": "100",
  "subject.account.name": "systemd-timesync",
  "subject.account.privileges": "100",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/bin/cp",
  "subject.process.id": "528048",
  "subject.process.meta": "cp -a /tmp/apt-key-gpghome.flyu5B8ZYq/pubring.gpg /tmp/apt-key-gpghome.flyu5B8ZYq/pubring.orig.gpg",
  "subject.process.name": "cp",
  "subject.process.parent.id": "528015",
  "subject.process.path": "/bin/",
  "time": "2022-05-24T14:10:44.000Z"
}