{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "28187",
  "datafield1": "setfacl",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_api_xattr",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "setxattr",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/etc/test",
  "object.id": "525526",
  "object.name": "test",
  "object.path": "/etc/",
  "object.property": "extended_attributes",
  "object.type": "executable_file",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "180",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/bin/setfacl",
  "subject.process.id": "2405",
  "subject.process.meta": "setfacl -m u:odmin:7 /etc/test",
  "subject.process.name": "setfacl",
  "subject.process.parent.id": "2096",
  "subject.process.path": "/bin/",
  "time": "2019-04-29T16:38:36.000Z"
}