{
  "action": "modify",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "10152",
  "datafield1": "systemd-journal",
  "datafield2": "root",
  "datafield3": "0640",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.rule": "pt_siem_api_xattr",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "fsetxattr",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.id": "38408",
  "object.property": "extended_attributes",
  "object.type": "regular_file",
  "reason": "Operation not supported",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/lib/systemd/systemd-journald",
  "subject.process.id": "1846",
  "subject.process.meta": "(journald)",
  "subject.process.name": "systemd-journald",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/lib/systemd/",
  "time": "2019-12-09T13:30:41.000Z"
}