{
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "744431690",
  "datafield1": "glfs_iotwr003",
  "datafield2": "unknown(101)",
  "datafield3": "0640",
  "event_src.category": "Operating system",
  "event_src.fqdn": "EDDS-APP03T.dom.local",
  "event_src.hostname": "EDDS-APP03T",
  "event_src.rule": "pt_siem_api_xattr",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "msgid": "fsetxattr",
  "numfield2": 101,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.id": "88782",
  "object.property": "extended_attributes",
  "object.type": "regular_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/glusterfsd",
  "subject.process.id": "19155",
  "subject.process.name": "glusterfsd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2020-12-03T09:40:49.000Z"
}