{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "2105140",
  "datafield1": "setfattr",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_xattr_change",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/2",
  "msgid": "setxattr",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/1",
  "object.id": "420266",
  "object.name": "1",
  "object.path": "/root/",
  "object.property": "extended_attributes",
  "object.type": "regular_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "2",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/setfattr",
  "subject.process.id": "8574",
  "subject.process.meta": "-zsh",
  "subject.process.name": "setfattr",
  "subject.process.parent.id": "1730",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-25T06:52:36.000Z"
}