{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.airport.airportd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_data_writing",
  "importance": "info",
  "msgid": "33",
  "object.fullpath": "/dev/null",
  "object.name": "null",
  "object.path": "/dev/",
  "subject.account.id": "0",
  "subject.account.session_id": "267",
  "subject.process.fullpath": "/usr/libexec/airportd",
  "subject.process.hash": "UNKNOWN:ACBC376B6DD9E3DD98491B40B8329EEB5E521DF7",
  "subject.process.id": "267",
  "subject.process.name": "airportd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T12:08:07.264Z"
}