{
  "subject": "process",
  "action": "info",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "501",
  "datafield10": "1",
  "datafield11": "UBF8T346G9",
  "datafield12": "5946",
  "datafield13": "5946",
  "datafield14": "6248",
  "datafield15": "false",
  "datafield16": "false",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "com.github.Electron.helper",
  "datafield8": "570491649",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_signal_sent_to_process",
  "importance": "info",
  "msgid": "31",
  "object.account.id": "501",
  "object.account.session_id": "1",
  "object.fullpath": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "object.name": "Code Helper (Plugin)",
  "object.path": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/",
  "object.process.fullpath": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "object.process.id": "6270",
  "object.process.name": "Code Helper (Plugin)",
  "object.process.parent.id": "6248",
  "object.process.path": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/",
  "object.property": "signal number sent to the target process",
  "object.value": "0",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "subject.process.hash": "UNKNOWN:C62A1E45726AD1393A6386FE42D662269BB427F8",
  "subject.process.id": "6270",
  "subject.process.name": "Code Helper (Plugin)",
  "subject.process.parent.id": "6248",
  "subject.process.path": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/",
  "time": "2023-07-24T12:07:22.265Z"
}