{
  "subject": "account",
  "action": "modify",
  "object": "db_object",
  "status": "success",
  "datafield1": "EXECUTE AS LOGIN = 'login1'; --Verify the execution context is now login1.",
  "datafield2": "WIN-KUR7C5KGUG8\\SQL2012",
  "datafield3": "master",
  "datafield4": "IMP",
  "datafield5": "SL",
  "event_src.category": "Database server",
  "event_src.hostname": "win-kur7c5kgug8",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_change_impersonation",
  "importance": "low",
  "msgid": "33205",
  "object.account.name": "login1",
  "object.name": "login1",
  "object.query": "EXECUTE AS LOGIN = 'login1'; --Verify the execution context is now login1.",
  "object.type": "current context",
  "subject.account.id": "01",
  "subject.account.name": "sa",
  "subject.id": "01",
  "subject.name": "sa",
  "time": "2015-10-02T10:09:22Z"
}