{
  "subject": "account",
  "action": "modify",
  "object": "db_object",
  "status": "success",
  "datafield1": "EXECUTE AS USER = 'user2'; --Display current execution context.",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "AdventureWorks2012",
  "datafield4": "IMP",
  "datafield5": "SU",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_change_impersonation",
  "importance": "low",
  "msgid": "33205",
  "object.account.name": "user2",
  "object.name": "user2",
  "object.query": "EXECUTE AS USER = 'user2'; --Display current execution context.",
  "object.type": "current context",
  "subject.account.id": "f891f9853b266e43af15e4ce9727ad46",
  "subject.account.name": "login1",
  "subject.id": "f891f9853b266e43af15e4ce9727ad46",
  "subject.name": "login1",
  "time": "2015-09-22T08:11:30Z"
}