{
  "subject": "account",
  "action": "execute",
  "object": "command",
  "status": "success",
  "datafield1": "EXEC sp_oamethod @shell, 'run', null, 'ipconfig', '0','True'",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "EX",
  "datafield5": "X",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_exec_used",
  "importance": "high",
  "msgid": "33205",
  "object.property": "command name",
  "object.query": "EXEC sp_oamethod @shell, 'run', null, 'ipconfig', '0','True'",
  "object.type": "system command usage",
  "object.value": "sp_OAMethod",
  "subject.account.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.account.name": "analysis",
  "subject.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.name": "analysis",
  "time": "2020-01-31T14:22:58Z"
}