{
  "subject": "account",
  "action": "modify",
  "object": "configuration",
  "status": "success",
  "datafield1": "EXEC sp_configure 'scan for startup procs', 1",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "EX",
  "datafield5": "P",
  "datafield8": "scan for startup procs",
  "datafield9": "1",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_exec_used",
  "importance": "high",
  "msgid": "33205",
  "object.property": "command name",
  "object.query": "EXEC sp_configure 'scan for startup procs', 1",
  "object.value": "sp_configure",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-03T15:06:58Z"
}