{
  "subject": "account",
  "action": "execute",
  "object": "command",
  "status": "success",
  "datafield1": "EXEC sp_helpuser",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "EX",
  "datafield5": "P",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_exec_used",
  "importance": "low",
  "msgid": "33205",
  "object.property": "command name",
  "object.query": "EXEC sp_helpuser",
  "object.type": "show database users",
  "object.value": "sp_helpuser",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-04T09:20:24Z"
}