{
  "subject": "account",
  "action": "execute",
  "object": "command",
  "status": "success",
  "datafield1": "EXEC msdb.dbo.sp_send_dbmail \t-- Созданный нами профиль администратора почтовых рассылок \t\t@profile_name = 'MySite Admin Mailer', \t-- Адрес получателя \t\t@recipients = 'friend@mysite.ru', \t-- Текст письма \t\t@body = N'Испытание системы SQL Server Database Mail', \t-- Тема \t\t@subject = N'Тестовое сообщение', \t-- Для примера добавим к письму результаты произвольного SQL-запроса \t\t@query = 'SELECT TOP 10 name FROM sys.objects'",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "msdb",
  "datafield4": "EX",
  "datafield5": "P",
  "datafield6": "friend@mysite.ru",
  "datafield7": "SELECT TOP 10 name FROM sys.objects",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_exec_used",
  "importance": "medium",
  "msgid": "33205",
  "object.property": "command name",
  "object.query": "EXEC msdb.dbo.sp_send_dbmail \t-- Созданный нами профиль администратора почтовых рассылок \t\t@profile_name = 'MySite Admin Mailer', \t-- Адрес получателя \t\t@recipients = 'friend@mysite.ru', \t-- Текст письма \t\t@body = N'Испытание системы SQL Server Database Mail', \t-- Тема \t\t@subject = N'Тестовое сообщение', \t-- Для примера добавим к письму результаты произвольного SQL-запроса \t\t@query = 'SELECT TOP 10 name FROM sys.objects'",
  "object.type": "sent query text",
  "object.value": "sp_send_dbmail",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-04T12:29:33Z"
}