{
  "subject": "process",
  "action": "access",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "501",
  "datafield10": "11223344556677889900",
  "datafield12": "5452",
  "datafield14": "2",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.zsh",
  "datafield8": "570510081",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_attempt_thread_creation",
  "importance": "info",
  "msgid": "11",
  "object.account.session_id": "5451",
  "object.fullpath": "/bin/zsh",
  "object.name": "zsh",
  "object.path": "/bin/",
  "subject.account.id": "501",
  "subject.account.session_id": "5451",
  "subject.process.fullpath": "/bin/zsh",
  "subject.process.hash": "UNKNOWN:6275A159AFDB73D6EE5837FFE745AED8F5180E36",
  "subject.process.id": "5452",
  "subject.process.name": "zsh",
  "subject.process.parent.id": "5451",
  "subject.process.path": "/bin/",
  "time": "2023-07-24T12:12:31.616Z"
}