{
  "subject": "process",
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield11": "UBF8T346G9",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "com.microsoft.VSCode.helper",
  "datafield8": "570503953",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_create_file",
  "importance": "info",
  "msgid": "13",
  "object.fullpath": "/Users/user/Library/Application Support/Code/Cache/Cache_Data/index-dir/temp-index",
  "object.name": "temp-index",
  "object.path": "/Users/user/Library/Application Support/Code/Cache/Cache_Data/index-dir/",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper",
  "subject.process.hash": "UNKNOWN:DA388EFF7A18FC5E26E969DAC493534A885E7BEC",
  "subject.process.id": "5950",
  "subject.process.name": "Code Helper",
  "subject.process.parent.id": "5946",
  "subject.process.path": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/",
  "time": "2023-07-24T12:02:17.644Z"
}