{
  "action": "execute",
  "object": "request",
  "status": "success",
  "datafield1": "3",
  "event_src.category": "Other",
  "event_src.hostname": "teamcity",
  "event_src.title": "teamcity",
  "event_src.vendor": "jetbrains",
  "id": "PT_JetBrains_TeamCity_syslog_Rest_Request_Finished",
  "importance": "medium",
  "numfield3": 1695845452620,
  "object.account.id": "-42",
  "object.account.privileges": "super_user",
  "object.process.meta": "no user-agent, authenticated as user with id=-42",
  "object.query": "/app/rest/users",
  "object.type": "GET",
  "src.ip": "10.125.3.2",
  "src.port": 57267,
  "time": "2023-09-27T20:10:52.620Z"
}