{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "269",
  "datafield2": "269",
  "datafield3": "4294967295",
  "datafield4": "269",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.ReportMemoryException",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_acl_modify",
  "importance": "info",
  "msgid": "82",
  "object.fullpath": "/private/var/db/reportmemoryexception",
  "object.name": "reportmemoryexception",
  "object.new_value": "!#acl 1\ngroup:ABCDEFAB-CDEF-ABCD-EFAB-CDEF000000F2:_nsurlsessiond:242:allow:execute",
  "object.path": "/private/var/db/",
  "object.property": "new access control list of file",
  "subject.account.id": "269",
  "subject.account.session_id": "12911",
  "subject.process.fullpath": "/usr/libexec/ReportMemoryException",
  "subject.process.hash": "UNKNOWN:4BDD766F52845766B7CFA8D035CB5B061A3B8FAE",
  "subject.process.id": "12911",
  "subject.process.name": "ReportMemoryException",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-25T07:35:28.761Z"
}