{
  "subject": "process",
  "action": "copy",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.DesktopServicesHelper",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_clone_file",
  "importance": "info",
  "msgid": "61",
  "object.fullpath": "/Users/user/Desktop/splitByEvents.py",
  "object.name": "splitByEvents.py",
  "object.new_value": "/Users/user/Desktop/splitByEvents copy.py",
  "object.path": "/Users/user/Desktop/",
  "object.property": "new fullpath",
  "subject.account.id": "501",
  "subject.account.session_id": "11289",
  "subject.process.fullpath": "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/Resources/DesktopServicesHelper",
  "subject.process.hash": "UNKNOWN:270D32BC0E5634259777ED1F1C71577978DAED95",
  "subject.process.id": "11289",
  "subject.process.name": "DesktopServicesHelper",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/Resources/",
  "time": "2023-07-24T14:50:15.936Z"
}