{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.logd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_setting_file_extended_attributes",
  "importance": "info",
  "msgid": "27",
  "object.fullpath": "/private/var/db/diagnostics/Persist/0000000000000159.tracev3",
  "object.name": "0000000000000159.tracev3",
  "object.path": "/private/var/db/diagnostics/Persist/",
  "object.property": "extended attributes",
  "object.type": "extended attributes",
  "object.value": "com.apple.logd.metadata",
  "subject.account.id": "0",
  "subject.account.session_id": "78",
  "subject.process.fullpath": "/usr/libexec/logd",
  "subject.process.hash": "UNKNOWN:7E991091C26A0A0F11EAB2D18B110BB4ED81E0FE",
  "subject.process.id": "78",
  "subject.process.name": "logd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T12:12:25.798Z"
}