{
  "subject": "process",
  "action": "stop",
  "object": "module",
  "status": "success",
  "category.generic": "Executable Module",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.kernelmanagerd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_kernel_extension_unloading",
  "importance": "info",
  "msgid": "18",
  "object.name": "com.vmware.kext.vmhgfs",
  "subject.account.id": "0",
  "subject.account.session_id": "108",
  "subject.process.fullpath": "/usr/libexec/kernelmanagerd",
  "subject.process.hash": "UNKNOWN:4916E9E82770F207A97A35C7D0828EF8D069829D",
  "subject.process.id": "108",
  "subject.process.name": "kernelmanagerd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T16:47:26.730Z"
}