{
  "subject": "account",
  "action": "modify",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "1032",
  "event_src.category": "Operating system",
  "event_src.hostname": "centos.local",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_mgmt",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "USER_MGMT",
  "object.name": "wheel",
  "object.property": "removed_user",
  "object.state": "deleting-user-from-shadow-group",
  "object.value": "unknown(1002)",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/sbin/userdel",
  "subject.process.id": "2248",
  "subject.process.name": "userdel",
  "subject.process.path": "/usr/sbin/",
  "time": "2020-10-19T08:54:03.000Z"
}