{
  "action": "modify",
  "object": "resource",
  "status": "success",
  "datafield1": "0",
  "datafield11": "EG7KH642X6",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "com.vmware.vmware-tools-daemon",
  "datafield8": "570490881",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_system_time_modification",
  "importance": "info",
  "msgid": "75",
  "object.type": "system time",
  "subject.account.id": "0",
  "subject.account.session_id": "12622",
  "subject.process.fullpath": "/Library/Application Support/VMware Tools/vmware-tools-daemon",
  "subject.process.hash": "UNKNOWN:9206F2D9BEE895411FB540732374AA041948850F",
  "subject.process.id": "12622",
  "subject.process.name": "vmware-tools-daemon",
  "subject.process.parent.id": "1",
  "subject.process.path": "/Library/Application Support/VMware Tools/",
  "time": "2023-07-24T16:47:28.991Z"
}