{
  "subject": "account",
  "action": "view",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "datafield1": "999",
  "datafield2": "1028",
  "datafield3": "C:\\Windows\\System32\\svchost.exe",
  "datafield4": "svchost.exe",
  "event_src.category": "Operating system",
  "event_src.fqdn": "abcd.qwer.tyui.local",
  "event_src.hostname": "abcd",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4799_Process_enumerates_members_of_security_enabled",
  "importance": "info",
  "msgid": "4799",
  "object.id": "S-1-5-32-544",
  "object.name": "Администраторы",
  "object.type": "local security-enabled",
  "subject.account.domain": "acme",
  "subject.account.id": "S-1-5-18",
  "subject.account.name": "astpchm096$",
  "subject.account.session_id": "999",
  "subject.domain": "acme",
  "subject.id": "S-1-5-18",
  "subject.name": "astpchm096$",
  "subject.process.fullpath": "C:\\Windows\\System32\\svchost.exe",
  "subject.process.id": "1028",
  "subject.process.name": "svchost.exe",
  "subject.process.path": "C:\\Windows\\System32\\",
  "time": "2017-08-14T07:18:03Z"
}