{
  "subject": "process",
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "65",
  "datafield2": "65",
  "datafield3": "4294967295",
  "datafield4": "65",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.mDNSResponder",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_removing",
  "importance": "info",
  "msgid": "32",
  "object.name": "mdsObject.db",
  "object.path": "/private/var/folders/zz/zyxvpxvq6csfxvn_n0000084000021/C/mds",
  "subject.account.id": "65",
  "subject.account.session_id": "231",
  "subject.process.fullpath": "/usr/sbin/mDNSResponder",
  "subject.process.hash": "UNKNOWN:E10F8093D9ED207F8746D934060E5B8CC6A7DFAC",
  "subject.process.id": "231",
  "subject.process.name": "mDNSResponder",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-07-24T12:12:25.755Z"
}