{
  "subject": "process",
  "action": "create",
  "object": "socket",
  "status": "success",
  "category.generic": "Socket",
  "category.high": "Network Management",
  "category.low": "Manipulation",
  "chain_id": "165097350",
  "datafield1": "uwsgi",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_api_socket",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "msgid": "socket",
  "object.account.group": "systemd-coredump",
  "object.account.id": "999",
  "object.account.name": "systemd-coredump",
  "object.domain": "AF_INET",
  "object.type": "SOCK_STREAM",
  "protocol": "IP",
  "subject.account.id": "999",
  "subject.account.name": "systemd-coredump",
  "subject.account.privileges": "999",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/local/bin/uwsgi",
  "subject.process.id": "10919",
  "subject.process.meta": "[Sentry] uWSGI http 1",
  "subject.process.name": "uwsgi",
  "subject.process.parent.id": "9982",
  "subject.process.path": "/usr/local/bin/",
  "time": "2022-05-21T11:59:39.000Z"
}