{
  "subject": "process",
  "action": "assign",
  "object": "socket",
  "status": "success",
  "category.generic": "Socket",
  "category.high": "Network Management",
  "category.low": "Manipulation",
  "chain_id": "560",
  "datafield1": "nginx",
  "dst.ip": "0.0.0.0",
  "dst.port": 8080,
  "event_src.category": "Operating system",
  "event_src.hostname": "test",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "bind",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.property": "socket_domain",
  "object.value": "AF_INET",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4",
  "subject.process.fullpath": "/usr/sbin/nginx",
  "subject.process.id": "3022",
  "subject.process.name": "nginx",
  "subject.process.parent.id": "3021",
  "subject.process.path": "/usr/sbin/",
  "time": "2019-04-29T16:06:08.000Z"
}