{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "380406",
  "datafield1": "apache2",
  "direction": "ingress",
  "dst.hostname": "ubuntu",
  "event_src.category": "Operating system",
  "event_src.hostname": "ubuntu",
  "event_src.rule": "pt_siem_api_accept",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "msgid": "accept4",
  "object.account.group": "33",
  "object.account.id": "33",
  "object.property": "socket_domain",
  "object.value": "AF_INET6",
  "src.ip": "10.126.255.3",
  "src.port": 42616,
  "subject.account.id": "33",
  "subject.account.privileges": "33",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/apache2",
  "subject.process.id": "2270",
  "subject.process.meta": "/usr/sbin/apache2 -k start",
  "subject.process.name": "apache2",
  "subject.process.parent.id": "1352",
  "subject.process.path": "/usr/sbin/",
  "time": "2019-05-21T14:31:00.000Z"
}