{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "55804695",
  "datafield1": "dbus-daemon",
  "direction": "ingress",
  "dst.ip": "10.0.176.77",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.176.77",
  "event_src.rule": "pt_siem_api_accept",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "accept4",
  "object.account.group": "messagebus",
  "object.account.id": "104",
  "object.account.name": "messagebus",
  "object.property": "socket_domain",
  "object.value": "AF_UNIX",
  "subject.account.id": "104",
  "subject.account.name": "messagebus",
  "subject.account.privileges": "104",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/bin/dbus-daemon",
  "subject.process.id": "526",
  "subject.process.meta": "/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only",
  "subject.process.name": "dbus-daemon",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/bin/",
  "time": "2022-06-03T13:13:49.000Z"
}