{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "58716",
  "datafield1": "http-nio-80-exe",
  "direction": "egress",
  "event_src.category": "Operating system",
  "event_src.ip": "10.156.26.71",
  "event_src.rule": "pt_siem_api_connect",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "connect",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.property": "socket_domain",
  "object.value": "AF_UNSPEC",
  "src.ip": "10.156.26.71",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/opt/openjdk-17/bin/java",
  "subject.process.id": "2140",
  "subject.process.meta": "java -jar /app.war",
  "subject.process.name": "java",
  "subject.process.parent.id": "2118",
  "subject.process.path": "/opt/openjdk-17/bin/",
  "time": "2022-05-17T07:18:53.000Z"
}