{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "26828",
  "datafield1": "salt-minion",
  "direction": "egress",
  "dst.ip": "10.0.52.101",
  "dst.port": 53,
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_api_connect",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "msgid": "connect",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.property": "socket_domain",
  "object.value": "AF_INET",
  "src.hostname": "debian-test",
  "subject.account.id": "0",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/bin/python2.7",
  "subject.process.id": "467",
  "subject.process.meta": "/usr/bin/python /usr/bin/salt-minion",
  "subject.process.name": "python2.7",
  "subject.process.parent.id": "449",
  "subject.process.path": "/usr/bin/",
  "time": "2019-04-29T16:06:35.000Z"
}