{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "failure",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "97030775",
  "datafield1": "Socket Thread",
  "direction": "egress",
  "dst.ip": "10.10.192.232",
  "dst.port": 443,
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.10.10",
  "event_src.rule": "pt_siem_api_connect",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "connect",
  "object.account.domain": "psec",
  "object.account.group": "domain users@ptsec",
  "object.account.id": "1702639807",
  "object.account.name": "userrch",
  "object.property": "socket_domain",
  "object.value": "AF_INET",
  "reason": "Operation now in progress",
  "src.ip": "10.10.10.10",
  "subject.account.domain": "psec",
  "subject.account.id": "1702639807",
  "subject.account.name": "userrch",
  "subject.account.privileges": "1702639807",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/lib/firefox-esr/firefox-esr",
  "subject.process.id": "2886783",
  "subject.process.meta": "/usr/bin/x-www-browser",
  "subject.process.name": "firefox-esr",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/lib/firefox-esr/",
  "time": "2022-10-03T16:02:12.000Z"
}