{
  "subject": "process",
  "action": "open",
  "object": "connection",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "chain_id": "7817970",
  "datafield1": "httpd",
  "direction": "ingress",
  "dst.ip": "127.0.0.1",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_api_accept",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "msgid": "accept4",
  "object.account.group": "apache",
  "object.account.id": "1000",
  "object.account.name": "apache",
  "object.property": "socket_domain",
  "object.value": "AF_INET6",
  "src.ip": "3.100.200.200",
  "src.port": 38000,
  "subject.account.id": "1000",
  "subject.account.name": "apache",
  "subject.account.privileges": "1000",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/httpd",
  "subject.process.id": "7030",
  "subject.process.name": "httpd",
  "subject.process.parent.id": "1594",
  "subject.process.path": "/usr/sbin/",
  "time": "2020-08-12T13:11:53.000Z"
}