{
  "subject": "process",
  "action": "create",
  "object": "socket",
  "status": "success",
  "category.generic": "Socket",
  "category.high": "Network Management",
  "category.low": "Manipulation",
  "chain_id": "24392",
  "datafield1": "audispd",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_api_socket",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_sockets",
  "importance": "low",
  "msgid": "socket",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.domain": "AF_UNIX",
  "object.type": "SOCK_DGRAM",
  "protocol": "IP",
  "subject.account.id": "0",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/sbin/audispd",
  "subject.process.id": "1881",
  "subject.process.meta": "/sbin/audispd",
  "subject.process.name": "audispd",
  "subject.process.parent.id": "1877",
  "subject.process.path": "/sbin/",
  "time": "2019-04-29T15:21:32.000Z"
}