{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "113812",
  "datafield1": "gpasswd",
  "datafield2": "root",
  "datafield3": "0640",
  "event_src.category": "Operating system",
  "event_src.ip": "10.125.136.66",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_attributes_modify",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "fchown",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.id": "787532",
  "object.new_value": "0 | 42",
  "object.property": "file_owner_uid | file_owner_gid",
  "object.type": "regular_file",
  "object.value": "0 | 42",
  "subject.account.id": "1001",
  "subject.account.name": "admin",
  "subject.account.privileges": "0",
  "subject.account.session_id": "208",
  "subject.process.fullpath": "/usr/bin/gpasswd",
  "subject.process.id": "188662",
  "subject.process.meta": "gpasswd -d www-data sudo",
  "subject.process.name": "gpasswd",
  "subject.process.parent.id": "188647",
  "subject.process.path": "/usr/bin/",
  "time": "2022-09-27T14:29:04.000Z"
}