{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "26159",
  "datafield1": "bash",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_root_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_attributes_modify",
  "importance": "medium",
  "logon_service": "pts/1",
  "msgid": "chown",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/root/.bash_history",
  "object.id": "1315210",
  "object.name": ".bash_history",
  "object.new_value": "0 | 0",
  "object.path": "/root/",
  "object.property": "file_owner_uid | file_owner_gid",
  "object.type": "regular_file",
  "object.value": "0 | 0",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "180",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/bin/bash",
  "subject.process.id": "2096",
  "subject.process.meta": "-bash",
  "subject.process.name": "bash",
  "subject.process.parent.id": "2095",
  "subject.process.path": "/bin/",
  "time": "2019-04-29T16:01:56.000Z"
}