{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "861080",
  "datafield1": "chmod",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_attributes_modify",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/7",
  "msgid": "fchmodat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/toor",
  "object.id": "420272",
  "object.name": "toor",
  "object.new_value": "0777",
  "object.path": "/root/",
  "object.property": "file_access_mode",
  "object.type": "regular_file",
  "object.value": "0644",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "11",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/chmod",
  "subject.process.id": "48126",
  "subject.process.meta": "chmod 777 toor",
  "subject.process.name": "chmod",
  "subject.process.parent.id": "3668",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-20T08:27:23.000Z"
}