{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "861082",
  "datafield1": "chgrp",
  "datafield2": "mpuser",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_attributes_modify",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/7",
  "msgid": "fchownat",
  "numfield2": 1000,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/toor",
  "object.id": "420272",
  "object.name": "toor",
  "object.new_value": "4294967295 | 100",
  "object.path": "/root/",
  "object.property": "file_owner_uid | file_owner_gid",
  "object.type": "executable_file",
  "object.value": "1000 | 0",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "11",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/chgrp",
  "subject.process.id": "48154",
  "subject.process.meta": "chgrp users toor",
  "subject.process.name": "chgrp",
  "subject.process.parent.id": "3668",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-20T08:27:53.000Z"
}