{
  "action": "configure",
  "object": "system",
  "status": "success",
  "chain_id": "391",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.216.222",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_system_runlevel",
  "importance": "info",
  "labels": "node_contains_ext_ip",
  "msgid": "SYSTEM_RUNLEVEL",
  "object.new_value": "5",
  "object.property": "runlevel",
  "object.value": "N",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/lib/systemd/systemd-update-utmp",
  "subject.process.id": "780",
  "subject.process.name": "systemd-update-utmp",
  "subject.process.path": "/usr/lib/systemd/",
  "time": "2023-04-17T21:18:30.000Z"
}