{
  "action": "remove",
  "object": "rule",
  "status": "success",
  "chain_id": "7912",
  "event_src.category": "Operating system",
  "event_src.ip": "2001:db8:1ab0:130:250:56ff:feaf:7e1a",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_config_change_rule",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "CONFIG_CHANGE",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.name": "pt_siem_api_accept",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/auditctl",
  "subject.process.id": "2911036",
  "subject.process.meta": "/sbin/auditctl -R /etc/audit/audit.rules",
  "subject.process.name": "auditctl",
  "subject.process.parent.id": "2911023",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-07-11T11:47:29.000Z"
}