{
  "action": "create",
  "object": "rule",
  "status": "success",
  "chain_id": "50",
  "event_src.category": "Operating system",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_config_change_rule",
  "importance": "low",
  "msgid": "CONFIG_CHANGE",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.name": "pt_siem_bin_modify",
  "object.property": "path_to_file",
  "object.type": "file_monitoring",
  "object.value": "/usr/local/bin",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/auditctl",
  "subject.process.id": "817",
  "subject.process.meta": "/sbin/auditctl -R /etc/audit/audit.rules",
  "subject.process.name": "auditctl",
  "subject.process.parent.id": "785",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-11-19T13:36:59.000Z"
}