{
  "subject": "process",
  "action": "elevate",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "60507463",
  "datafield1": "sshd",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.20.20",
  "event_src.rule": "pt_siem_api_caps",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_capabilities_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "capset",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.new_value": "0000003fffffffff",
  "object.process.id": "125937",
  "object.property": "effective_capabilities",
  "object.state": "capabilities_change",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/sshd",
  "subject.process.id": "125937",
  "subject.process.meta": "/usr/sbin/sshd -D -R",
  "subject.process.name": "sshd",
  "subject.process.parent.id": "648",
  "subject.process.path": "/usr/sbin/",
  "time": "2021-08-24T06:00:49.000Z"
}