{
  "subject": "process",
  "action": "elevate",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "2924",
  "datafield1": "gnome-keyring-d",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_capabilities_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "capset",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.new_value": "00000000000040c0",
  "object.process.id": "1349",
  "object.property": "effective_capabilities",
  "object.state": "capabilities_change",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4",
  "subject.process.fullpath": "/usr/bin/gnome-keyring-daemon",
  "subject.process.id": "1349",
  "subject.process.meta": "/usr/bin/gnome-keyring-daemon --start --components=ssh",
  "subject.process.name": "gnome-keyring-daemon",
  "subject.process.parent.id": "1308",
  "subject.process.path": "/usr/bin/",
  "time": "2020-02-14T11:32:27.000Z"
}