{
  "subject": "process",
  "action": "elevate",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "24316507",
  "datafield1": "(netdata)",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.52.30",
  "event_src.rule": "pt_siem_api_caps",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_capabilities_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "capset",
  "object.account.group": "netdata",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.new_value": "0000003fffffffff",
  "object.process.id": "90561",
  "object.property": "effective_capabilities",
  "object.state": "capabilities_change",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/lib/systemd/systemd",
  "subject.process.id": "90561",
  "subject.process.meta": "(netdata)",
  "subject.process.name": "systemd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/lib/systemd/",
  "time": "2021-08-24T06:23:55.000Z"
}