{
  "subject": "account",
  "action": "close",
  "object": "session",
  "status": "success",
  "category.generic": "Connection",
  "category.high": "Network Interaction Management",
  "category.low": "Communication",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "501",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.sshd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_user_openssh_logout",
  "importance": "info",
  "msgid": "121",
  "src.ip": "192.168.163.1",
  "subject.account.id": "501",
  "subject.account.name": "user",
  "subject.process.fullpath": "/usr/sbin/sshd",
  "subject.process.hash": "UNKNOWN:7F5C5E50AD1A8C11F4ACFD6331376B9307DC9302",
  "subject.process.id": "12527",
  "subject.process.name": "sshd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-07-25T07:36:36.769Z"
}