{
  "subject": "account",
  "action": "modify",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "1250",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "USER_ACCT",
  "object.name": "nginx",
  "object.new_value": "jr,syslog",
  "object.property": "members",
  "object.state": "members of group nginx set by root to jr,syslog",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/bin/gpasswd",
  "subject.process.id": "2051",
  "subject.process.name": "gpasswd",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-29T08:07:07.000Z"
}