{
  "subject": "account",
  "action": "modify",
  "object": "account",
  "status": "success",
  "category.generic": "Operating System",
  "category.high": "Access Management",
  "category.low": "Communication",
  "chain_id": "1250",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "USER_ACCT",
  "object.account.id": "1000",
  "object.account.name": "jr",
  "object.property": "failed_logins_counter",
  "object.state": "pam_tally2",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/sbin/pam_tally2",
  "subject.process.id": "1380",
  "subject.process.name": "pam_tally2",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-29T08:07:07.000Z"
}