{
  "subject": "account",
  "action": "modify",
  "object": "user_group",
  "status": "ongoing",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "1685",
  "event_src.category": "Operating system",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "USER_ACCT",
  "object.name": "test1",
  "object.new_value": "test11",
  "object.property": "name",
  "object.state": "changing /etc/gshadow; group test1, new name: test11",
  "object.value": "test1",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "2",
  "subject.process.fullpath": "/usr/sbin/groupmod",
  "subject.process.id": "1735",
  "subject.process.name": "groupmod",
  "subject.process.path": "/usr/sbin/",
  "time": "2020-10-22T14:25:04.000Z"
}