{
  "subject": "account",
  "action": "elevate",
  "object": "account",
  "status": "ongoing",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "522",
  "event_src.category": "Operating system",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_acct",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "USER_ACCT",
  "object.account.name": "test1",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.process.fullpath": "/usr/bin/su",
  "subject.process.id": "2598",
  "subject.process.name": "su",
  "subject.process.path": "/usr/bin/",
  "subject.state": "PAM:accounting",
  "time": "2020-10-16T07:50:19.000Z"
}