{
  "subject": "account",
  "action": "grant",
  "object": "db_object",
  "status": "success",
  "datafield1": "alter server role [serveradmin] add member [bobby]",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "master",
  "datafield4": "APRL",
  "datafield5": "SG",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_role_member_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "serveradmin",
  "object.property": "affected entity",
  "object.query": "alter server role [serveradmin] add member [bobby]",
  "object.type": "role",
  "object.value": "bobby",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-21T15:10:21Z"
}