{
  "action": "stop",
  "object": "process",
  "status": "success",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.BlueTool",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_exiting",
  "importance": "info",
  "msgid": "15",
  "object.account.id": "0",
  "object.account.session_id": "7954",
  "object.process.fullpath": "/usr/sbin/BlueTool",
  "object.process.id": "7954",
  "object.process.name": "BlueTool",
  "object.process.parent.id": "1",
  "object.process.path": "/usr/sbin/",
  "object.state": "256",
  "subject.process.hash": "UNKNOWN:1E1360E867D1B69B5B9EB2B52E49B0DB41D2C6D5",
  "time": "2023-07-24T12:12:24.680Z"
}