{
  "action": "start",
  "object": "service",
  "status": "success",
  "category.generic": "Service",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "9411",
  "event_src.category": "Operating system",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_daemon_start",
  "importance": "info",
  "msgid": "DAEMON_START",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.id": "697",
  "object.name": "auditd",
  "object.property": "event_format",
  "object.value": "enriched",
  "object.version": "2.8.4",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2022-07-11T02:34:05.000Z"
}