{
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "367254866",
  "datafield1": "atd",
  "datafield2": "teamcity",
  "datafield3": "0700",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.221",
  "event_src.rule": "pt_siem_cron_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_create",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "link",
  "numfield2": 2001,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/var/spool/cron/atjobs/=1358f01a45294",
  "object.id": "260976",
  "object.name": "=1358f01a45294",
  "object.path": "/var/spool/cron/atjobs/",
  "object.storage.fullpath": "/var/spool/cron/atjobs/a1358f01a45294",
  "object.storage.id": "260976",
  "object.storage.name": "a1358f01a45294",
  "object.storage.path": "/var/spool/cron/atjobs/",
  "object.type": "executable_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/var/spool/cron/atjobs",
  "subject.process.fullpath": "/usr/sbin/atd",
  "subject.process.id": "1174",
  "subject.process.meta": "/usr/sbin/atd -f",
  "subject.process.name": "atd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-05-17T08:20:00.000Z"
}