{
  "action": "create",
  "object": "link",
  "status": "success",
  "category.generic": "Link",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "10460",
  "datafield1": "insserv",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.176.129",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_create",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "symlinkat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/etc/rc3.d/S02docker",
  "object.id": "263706",
  "object.name": "S02docker",
  "object.path": "/etc/rc3.d/",
  "object.storage.fullpath": "/etc/rc3.d/../init.d/docker",
  "object.storage.name": "docker",
  "object.storage.path": "/etc/rc3.d/../init.d/",
  "object.type": "symlink",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/etc/rc3.d",
  "subject.process.fullpath": "/usr/lib/insserv/insserv",
  "subject.process.id": "10518",
  "subject.process.meta": "/usr/lib/insserv/insserv docker",
  "subject.process.name": "insserv",
  "subject.process.parent.id": "10517",
  "subject.process.path": "/usr/lib/insserv/",
  "time": "2022-05-23T07:20:21.000Z"
}