{
  "subject": "account",
  "action": "create",
  "object": "link",
  "status": "success",
  "category.generic": "Link",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "861075",
  "datafield1": "ln",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_create",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/7",
  "msgid": "symlinkat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/toor",
  "object.id": "420272",
  "object.name": "toor",
  "object.path": "/root/",
  "object.storage.fullpath": "/root/1",
  "object.storage.name": "1",
  "object.storage.path": "/root/",
  "object.type": "symlink",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "11",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/ln",
  "subject.process.id": "48094",
  "subject.process.meta": "ln -sf 1 toor",
  "subject.process.name": "ln",
  "subject.process.parent.id": "3668",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-20T08:26:48.000Z"
}