{
  "subject": "account",
  "action": "create",
  "object": "link",
  "status": "success",
  "category.generic": "Link",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "1123546",
  "datafield1": "dpkg",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_lib_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_create",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "symlink",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.dpkg-new",
  "object.id": "1967916",
  "object.name": "libQt5Xml.so.5.dpkg-new",
  "object.path": "/usr/lib/x86_64-linux-gnu/",
  "object.storage.fullpath": "/usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.15.8",
  "object.storage.name": "libQt5Xml.so.5.15.8",
  "object.storage.path": "/usr/lib/x86_64-linux-gnu/",
  "object.type": "symlink",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1761",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/bin/dpkg",
  "subject.process.id": "454482",
  "subject.process.meta": "/usr/bin/dpkg --force-confdef --force-confold --status-fd 19 --no-triggers --unpack --auto-deconfigure --recursive /tmp/apt-dpkg",
  "subject.process.name": "dpkg",
  "subject.process.parent.id": "453905",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-05T17:23:56.000Z"
}