{
  "subject": "account",
  "action": "modify",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "6532",
  "event_src.category": "Operating system",
  "event_src.hostname": "ubuntu2004",
  "event_src.ip": "127.0.0.1",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_chauthtok",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "USER_CHAUTHTOK",
  "object.name": "jr",
  "object.property": "password",
  "object.state": "password of group jr removed by root",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/bin/gpasswd",
  "subject.process.id": "12625",
  "subject.process.name": "gpasswd",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-29T10:35:25.000Z"
}