{
  "subject": "account",
  "action": "modify",
  "object": "account",
  "status": "success",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "880",
  "event_src.category": "Operating system",
  "event_src.hostname": "centos.local",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_chauthtok",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "USER_CHAUTHTOK",
  "object.account.name": "test1",
  "object.state": "PAM:chauthtok",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/bin/passwd",
  "subject.process.id": "2432",
  "subject.process.name": "passwd",
  "subject.process.path": "/usr/bin/",
  "time": "2020-10-16T07:53:58.000Z"
}