{
  "subject": "account",
  "action": "restore",
  "object": "database",
  "status": "success",
  "datafield1": "RESTORE DATABASE [secret] FILE = N'secret' FROM  DISK = N'C:\\Program Files\\Microsoft SQL Server\\MSSQL11.MSSQLSERVER\\MSSQL\\Backup\\secret.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 10",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "secret",
  "datafield4": "RS",
  "datafield5": "DB",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "low",
  "msgid": "33205",
  "object.name": "secret",
  "object.query": "RESTORE DATABASE [secret] FILE = N'secret' FROM  DISK = N'C:\\Program Files\\Microsoft SQL Server\\MSSQL11.MSSQLSERVER\\MSSQL\\Backup\\secret.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 10",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T08:53:48Z"
}