{
  "subject": "account",
  "action": "modify",
  "object": "configuration",
  "status": "success",
  "datafield1": "ALTER AUTHORIZATION on database::secret to bobby",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "secret",
  "datafield4": "TO",
  "datafield5": "DB",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "secret",
  "object.property": "target username",
  "object.query": "ALTER AUTHORIZATION on database::secret to bobby",
  "object.value": "bobby",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T14:06:28Z"
}