{
  "subject": "account",
  "action": "modify",
  "object": "configuration",
  "status": "success",
  "datafield1": "ALTER DATABASE TESTDB SET ENCRYPTION OFF",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "TestDB",
  "datafield4": "AL",
  "datafield5": "DB",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "high",
  "msgid": "33205",
  "object.property": "ENCRYPTION",
  "object.query": "ALTER DATABASE TESTDB SET ENCRYPTION OFF",
  "object.value": "OFF",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-03T15:20:06Z"
}