{
  "subject": "account",
  "action": "backup",
  "object": "resource",
  "status": "success",
  "datafield1": "BACKUP CERTIFICATE Certic TO FILE = 'C:\\Certic.cer' WITH PRIVATE KEY( FILE = 'C:\\Certic.key', ENCRYPTION BY PASSWORD = '******', DECRYPTION BY PASSWORD = '******' );",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "BA",
  "datafield5": "CR",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "high",
  "msgid": "33205",
  "object.name": "Certic",
  "object.path": "C:\\Certic.cer",
  "object.query": "BACKUP CERTIFICATE Certic TO FILE = 'C:\\Certic.cer' WITH PRIVATE KEY( FILE = 'C:\\Certic.key', ENCRYPTION BY PASSWORD = '******', DECRYPTION BY PASSWORD = '******' );",
  "object.type": "certificate",
  "subject.account.domain": "desktop-gb13g7p",
  "subject.account.id": "0105000000000005150000001df2aabab1fc830d139cadf1ea030000",
  "subject.account.name": "administrator",
  "subject.domain": "desktop-gb13g7p",
  "subject.id": "0105000000000005150000001df2aabab1fc830d139cadf1ea030000",
  "subject.name": "administrator",
  "time": "2020-03-06T07:53:48Z"
}