{
  "subject": "account",
  "action": "backup",
  "object": "database",
  "status": "success",
  "datafield1": "BACKUP DATABASE [TestDB] TO DISK = N'C:\\Backup' WITH NOFORMAT, NOINIT, NAME = N'TestDB-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "TestDB",
  "datafield4": "BA",
  "datafield5": "DB",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "low",
  "msgid": "33205",
  "object.name": "TestDB",
  "object.path": "C:\\Backup",
  "object.query": "BACKUP DATABASE [TestDB] TO DISK = N'C:\\Backup' WITH NOFORMAT, NOINIT, NAME = N'TestDB-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-04T07:50:26Z"
}