{
  "subject": "account",
  "action": "backup",
  "object": "resource",
  "status": "failure",
  "datafield1": "BACKUP MASTER KEY TO FILE = 'C:\\DbMasterKey1.key' ENCRYPTION BY PASSWORD = '******'",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "BA",
  "datafield5": "MK",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_database_operation",
  "importance": "high",
  "msgid": "33205",
  "object.path": "C:\\DbMasterKey1.key",
  "object.query": "BACKUP MASTER KEY TO FILE = 'C:\\DbMasterKey1.key' ENCRYPTION BY PASSWORD = '******'",
  "object.type": "master key",
  "subject.account.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.account.name": "hackerlooser",
  "subject.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.name": "hackerlooser",
  "time": "2020-03-06T08:02:15Z"
}