{
  "subject": "account",
  "action": "modify",
  "object": "account",
  "status": "success",
  "datafield1": "ALTER LOGIN [User13] WITH PASSWORD=N'******' MUST_CHANGE",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "master",
  "datafield4": "PWMC",
  "datafield5": "SL",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_credentials_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.account.name": "user13",
  "object.name": "user13",
  "object.property": "changed value",
  "object.query": "ALTER LOGIN [User13] WITH PASSWORD=N'******' MUST_CHANGE",
  "object.value": "need to change password",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T13:38:02Z"
}