{
  "subject": "account",
  "action": "modify",
  "object": "account",
  "status": "success",
  "datafield1": "ALTER LOGIN [logoff1] WITH DEFAULT_DATABASE=[testo], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON",
  "datafield2": "WIN-KUR7C5KGUG8",
  "datafield3": "master",
  "datafield4": "PWEX",
  "datafield5": "SL",
  "event_src.category": "Database server",
  "event_src.hostname": "win-kur7c5kgug8",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_credentials_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.account.name": "logoff1",
  "object.name": "logoff1",
  "object.property": "changed value",
  "object.query": "ALTER LOGIN [logoff1] WITH DEFAULT_DATABASE=[testo], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON",
  "object.value": "password expiration",
  "subject.account.id": "989004c01749624d9c451a05ffc7f806",
  "subject.account.name": "admin",
  "subject.id": "989004c01749624d9c451a05ffc7f806",
  "subject.name": "admin",
  "time": "2015-10-20T12:07:45Z"
}