{
  "action": "info",
  "object": "file_object",
  "status": "success",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.xpc.launchd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_descriptor_duplicated",
  "importance": "info",
  "msgid": "73",
  "object.fullpath": "/dev/console",
  "object.name": "console",
  "object.path": "/dev/",
  "object.type": "file descriptor",
  "subject.account.id": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/sbin/launchd",
  "subject.process.hash": "UNKNOWN:F7618A048AA74CE1EA04F2AC56D3854B5E824548",
  "subject.process.id": "1",
  "subject.process.name": "launchd",
  "subject.process.parent.id": "0",
  "subject.process.path": "/sbin/",
  "time": "2023-07-24T11:42:18.844Z"
}