{
  "subject": "process",
  "action": "read",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.ls",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_multiple_extended_attributes_retrieval",
  "importance": "info",
  "msgid": "66",
  "object.fullpath": "/Users/user/Desktop/es_results2/all.json",
  "object.name": "all.json",
  "object.path": "/Users/user/Desktop/es_results2/",
  "object.type": "extended attributes",
  "subject.account.id": "501",
  "subject.account.session_id": "5451",
  "subject.process.fullpath": "/bin/ls",
  "subject.process.hash": "UNKNOWN:D1DA507DDFEADCDF696C1D94532E725B2871524D",
  "subject.process.id": "7994",
  "subject.process.name": "ls",
  "subject.process.parent.id": "5452",
  "subject.process.path": "/bin/",
  "time": "2023-07-24T12:12:27.859Z"
}