{
  "subject": "account",
  "action": "elevate",
  "object": "process",
  "status": "success",
  "chain_id": "36479",
  "datafield1": "sudo",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.220.166",
  "event_src.rule": "pt_siem_api_setuid",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_setids",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/12",
  "msgid": "setresuid",
  "object.account.group": "user",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.new_value": "x | 0 | x",
  "object.process.fullpath": "/usr/bin/sudo",
  "object.process.id": "3030810",
  "object.process.name": "sudo",
  "object.process.parent.id": "2892378",
  "object.process.path": "/usr/bin/",
  "object.property": "ruid | euid | suid",
  "object.value": "1000 | 0 | 0",
  "subject.account.id": "1000",
  "subject.account.name": "user",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/bin/sudo",
  "subject.process.id": "3030810",
  "subject.process.meta": "sudo echo",
  "subject.process.name": "sudo",
  "subject.process.parent.id": "2892378",
  "subject.process.path": "/usr/bin/",
  "time": "2023-02-15T05:31:19.000Z"
}