{
  "subject": "account",
  "action": "elevate",
  "object": "process",
  "status": "success",
  "chain_id": "9428",
  "datafield1": "dpkg",
  "event_src.category": "Operating system",
  "event_src.hostname": "pewpew-pc",
  "event_src.rule": "pt_siem_api_setuid",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_setids",
  "importance": "medium",
  "logon_service": "pts/1",
  "msgid": "setgid",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.new_value": "0 | 0 | 0",
  "object.process.fullpath": "/usr/bin/dpkg",
  "object.process.id": "4429",
  "object.process.name": "dpkg",
  "object.process.parent.id": "4404",
  "object.process.path": "/usr/bin/",
  "object.property": "rgid | egid | sgid",
  "object.value": "0",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "61",
  "subject.process.fullpath": "/usr/bin/dpkg",
  "subject.process.id": "4429",
  "subject.process.meta": "/usr/bin/python /usr/bin/salt-call --local --retcode-passthrough -l debug --log-file-level debug --file-root /opt/pt/mpsiem-stor",
  "subject.process.name": "dpkg",
  "subject.process.parent.id": "4404",
  "subject.process.path": "/usr/bin/",
  "time": "2019-05-18T20:55:38.000Z"
}