{
  "action": "elevate",
  "object": "process",
  "status": "success",
  "chain_id": "361080",
  "datafield1": "master",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.151",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_setids",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "msgid": "setuid",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.new_value": "0 | 0 | 0",
  "object.process.fullpath": "/usr/lib/postfix/bin/master",
  "object.process.id": "1876",
  "object.process.name": "master",
  "object.process.parent.id": "1",
  "object.process.path": "/usr/lib/postfix/bin/",
  "object.property": "ruid | euid | suid",
  "object.value": "0",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/lib/postfix/bin/master",
  "subject.process.id": "1876",
  "subject.process.meta": "/usr/lib/postfix/bin//master -w",
  "subject.process.name": "master",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/lib/postfix/bin/",
  "time": "2020-02-14T18:18:28.000Z"
}