{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "0",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.sudo",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_effective_group_id_setting",
  "importance": "info",
  "msgid": "106",
  "object.account.id": "0",
  "object.account.session_id": "5451",
  "object.group": "0",
  "object.process.fullpath": "/usr/bin/sudo",
  "object.process.id": "8012",
  "object.process.name": "sudo",
  "object.process.parent.id": "8009",
  "object.process.path": "/usr/bin/",
  "subject.account.id": "0",
  "subject.account.session_id": "5451",
  "subject.process.fullpath": "/usr/bin/sudo",
  "subject.process.hash": "UNKNOWN:F32D25C4DD678BEEC84461728282202284C968E0",
  "subject.process.id": "8012",
  "subject.process.name": "sudo",
  "subject.process.parent.id": "8009",
  "subject.process.path": "/usr/bin/",
  "time": "2023-07-24T12:12:42.623Z"
}