{
  "subject": "account",
  "action": "create",
  "object": "account",
  "status": "success",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "708",
  "event_src.category": "Operating system",
  "event_src.hostname": "centos.local",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_add_user",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "ADD_USER",
  "object.account.id": "1002",
  "object.account.name": "unknown(1002)",
  "object.state": "add-user",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/usr/sbin/useradd",
  "subject.process.id": "2368",
  "subject.process.name": "useradd",
  "subject.process.path": "/usr/sbin/",
  "time": "2020-10-16T07:52:47.000Z"
}