{
  "subject": "account",
  "action": "create",
  "object": "account",
  "status": "failure",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "2243",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian10siem",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_add_user",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "ADD_USER",
  "object.account.name": "user",
  "object.state": "adding user",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4",
  "subject.process.fullpath": "/usr/sbin/useradd",
  "subject.process.id": "1483",
  "subject.process.name": "useradd",
  "subject.process.path": "/usr/sbin/",
  "time": "2019-12-09T03:56:58.000Z"
}