{
  "action": "create",
  "object": "account",
  "status": "ongoing",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "61323059",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.177.128",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_add_user",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "ADD_USER",
  "object.account.id": "999",
  "object.account.name": "systemd-coredump",
  "object.state": "adding home directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/useradd",
  "subject.process.id": "16726",
  "subject.process.name": "useradd",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-26T09:03:53.000Z"
}