{
  "action": "modify",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "30487506",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_add_user",
  "importance": "low",
  "msgid": "ADD_USER",
  "object.new_value": "chrome",
  "object.property": "added_user",
  "object.state": "adding user to group",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/useradd",
  "subject.process.id": "29288",
  "subject.process.name": "useradd",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-26T09:16:54.000Z"
}