{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "success",
  "datafield1": "select name, is_encrypted from sys.databases",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "SL",
  "datafield5": "V",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "low",
  "msgid": "33205",
  "object.name": "databases",
  "object.property": "encryption configuration",
  "object.query": "select name, is_encrypted from sys.databases",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-04T07:18:21Z"
}