{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "success",
  "datafield1": "SELECT name, password_hash FROM master.sys.sql_logins",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "SL",
  "datafield5": "U",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "syspalnames",
  "object.property": "credentials",
  "object.query": "SELECT name, password_hash FROM master.sys.sql_logins",
  "subject.account.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.account.name": "analysis",
  "subject.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.name": "analysis",
  "time": "2020-01-31T13:35:41Z"
}