{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "success",
  "datafield1": "SELECT * FROM sys.server_audit_specifications",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "SL",
  "datafield5": "V",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "low",
  "msgid": "33205",
  "object.name": "server_audit_specifications",
  "object.property": "audit configuration",
  "object.query": "SELECT * FROM sys.server_audit_specifications",
  "subject.account.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.account.name": "analysis",
  "subject.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.name": "analysis",
  "time": "2020-01-31T13:05:21Z"
}