{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "failure",
  "datafield1": "SELECT name,type_desc,is_disabled, create_date FROM master.sys.server_principals WHERE IS_SRVROLEMEMBER ('sysadmin',name) = 1 ORDER BY name",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "SL",
  "datafield5": "V",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "server_principals",
  "object.property": "credentials",
  "object.query": "SELECT name,type_desc,is_disabled, create_date FROM master.sys.server_principals WHERE IS_SRVROLEMEMBER ('sysadmin',name) = 1 ORDER BY name",
  "subject.account.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.account.name": "hackerlooser",
  "subject.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.name": "hackerlooser",
  "time": "2020-03-05T15:32:42Z"
}