{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "success",
  "datafield1": "SELECT co.name AS column_name,\n\t\tta.name AS table_name,\n\t\tSCHEMA_NAME(schema_id) AS schema_name\n\tFROM sys.tables AS ta\n\t\tINNER JOIN sys.all_columns co ON ta.OBJECT_ID = co.OBJECT_ID\n\tWHERE co.name LIKE '%hackpattern%'",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "SL",
  "datafield5": "V",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "tables",
  "object.property": "pattern search",
  "object.query": "SELECT co.name AS column_name,\n\t\tta.name AS table_name,\n\t\tSCHEMA_NAME(schema_id) AS schema_name\n\tFROM sys.tables AS ta\n\t\tINNER JOIN sys.all_columns co ON ta.OBJECT_ID = co.OBJECT_ID\n\tWHERE co.name LIKE '%hackpattern%'",
  "object.value": "%hackpattern%",
  "subject.account.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.account.name": "analysis",
  "subject.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.name": "analysis",
  "time": "2020-02-04T08:45:44Z"
}