{
  "subject": "account",
  "action": "view",
  "object": "db_object",
  "status": "success",
  "datafield1": "select top 5 a.server_name, a.database_name, backup_finish_date, a.backup_size, CASE a.[type] -- Let's decode the three main types of backup here  WHEN 'D' THEN 'Full'  WHEN 'I' THEN 'Differential'  WHEN 'L' THEN 'Transaction Log'  ELSE a.[type] END as BackupType  ,b.physical_device_name from msdb.dbo.backupset a join msdb.dbo.backupmediafamily b on a.media_set_id = b.media_set_id order by a.backup_finish_date desc",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "msdb",
  "datafield4": "SL",
  "datafield5": "U",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_request_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "backupmediafamily",
  "object.property": "backup location",
  "object.query": "select top 5 a.server_name, a.database_name, backup_finish_date, a.backup_size, CASE a.[type] -- Let's decode the three main types of backup here  WHEN 'D' THEN 'Full'  WHEN 'I' THEN 'Differential'  WHEN 'L' THEN 'Transaction Log'  ELSE a.[type] END as BackupType  ,b.physical_device_name from msdb.dbo.backupset a join msdb.dbo.backupmediafamily b on a.media_set_id = b.media_set_id order by a.backup_finish_date desc",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-04T08:56:02Z"
}