{
  "action": "update",
  "object": "package",
  "status": "success",
  "chain_id": "102878092",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.177.125",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_software_update",
  "importance": "info",
  "labels": "node_contains_ext_ip",
  "msgid": "SOFTWARE_UPDATE",
  "object.name": "ed-1.9-4.el7.x86_64",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/bin/python2.7",
  "subject.process.id": "33701",
  "subject.process.name": "python2.7",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-10T16:00:24.000Z"
}