{
  "subject": "process",
  "action": "access",
  "object": "module",
  "status": "success",
  "category.generic": "Executable Module",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.finder",
  "datafield8": "570522369",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_open_IOKit_device",
  "importance": "info",
  "msgid": "24",
  "object.name": "AppleAPFSUserClient",
  "object.type": "0",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder",
  "subject.process.hash": "UNKNOWN:388AD9EC55521C0054C87735CDAA6DFE33DCC599",
  "subject.process.id": "385",
  "subject.process.name": "Finder",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/CoreServices/Finder.app/Contents/MacOS/",
  "time": "2023-07-24T12:03:47.003Z"
}