{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "999",
  "datafield3": "C:\\Windows\\servicing\\",
  "datafield4": "TrustedInstaller.exe",
  "datafield6": "C:\\Windows\\servicing\\TrustedInstaller.exe",
  "event_src.category": "Operating system",
  "event_src.fqdn": "2008r2sp1-av.ad2008r2.ru",
  "event_src.hostname": "2008r2sp1-av",
  "event_src.id": "Microsoft-Windows-Security-Auditing",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_Common_Security_4907_Auditing_settings_on_object_were_changed",
  "importance": "info",
  "msgid": "4907",
  "object.fullpath": "c:\\windows\\system32\\spp\\tokens\\ppdlic\\telnet-server-ppdlic.xrm-ms",
  "object.name": "telnet-server-ppdlic.xrm-ms",
  "object.new_value": "s:arai(au;safa;dclcrpcrsdwdwo;;;wd)",
  "object.path": "c:\\windows\\system32\\spp\\tokens\\ppdlic\\",
  "object.property": "security descriptor",
  "object.type": "attribute",
  "reason": "s:arai(au;safa;dclcrpcrsdwdwo;;;wd)",
  "subject.account.domain": "ad2008r2",
  "subject.account.name": "2008r2sp1-av$",
  "subject.account.session_id": "999",
  "subject.domain": "ad2008r2",
  "subject.name": "2008r2sp1-av$",
  "subject.process.fullpath": "C:\\Windows\\servicing\\TrustedInstaller.exe",
  "subject.process.id": "4432",
  "subject.process.name": "TrustedInstaller.exe",
  "subject.process.path": "C:\\Windows\\servicing\\",
  "time": "2015-12-01T13:35:57.351Z"
}