{
  "action": "start",
  "object": "module",
  "status": "success",
  "category.generic": "Executable Module",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "1594",
  "datafield1": "modprobe",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.176.130",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_kernel_module",
  "importance": "medium",
  "labels": "node_contains_ext_ip",
  "msgid": "finit_module",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.state": "kernel_module_change",
  "object.type": "executable_module",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/bin/kmod",
  "subject.process.id": "2603",
  "subject.process.meta": "/sbin/modprobe -q -- iptable_nat",
  "subject.process.name": "kmod",
  "subject.process.parent.id": "40",
  "subject.process.path": "/bin/",
  "time": "2022-05-20T13:19:09.000Z"
}