{
  "subject": "account",
  "action": "start",
  "object": "module",
  "status": "success",
  "category.generic": "Executable Module",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "33440",
  "datafield1": "modprobe",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_api_kernel_mods",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_kernel_module",
  "importance": "medium",
  "logon_service": "pts/1",
  "msgid": "finit_module",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.name": "zstd_compress",
  "object.state": "kernel_module_change",
  "object.type": "executable_module",
  "subject.account.id": "1000",
  "subject.account.name": "cm",
  "subject.account.privileges": "0",
  "subject.account.session_id": "5",
  "subject.process.fullpath": "/usr/bin/kmod",
  "subject.process.id": "6354",
  "subject.process.meta": "modprobe btrfs",
  "subject.process.name": "kmod",
  "subject.process.parent.id": "6313",
  "subject.process.path": "/usr/bin/",
  "time": "2022-05-20T05:30:00.000Z"
}