{
  "subject": "process",
  "action": "update",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.WebKit.Networking",
  "datafield8": "570522369",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_provider_update",
  "importance": "info",
  "msgid": "19",
  "object.fullpath": "/Users/user/Library/Containers/com.apple.Safari/Data/Library/Caches/com.apple.Safari/WebKitCache/Version 16/Records/3FBA4ABED068FD267A319533D52D88DB6B1EA740/Resource",
  "object.name": "Resource",
  "object.new_value": "A7485B02509A4FD1A65C114A5BAA5915E6AEB2FE-blob",
  "object.path": "/Users/user/Library/Containers/com.apple.Safari/Data/Library/Caches/com.apple.Safari/WebKitCache/Version 16/Records/3FBA4ABED068FD267A319533D52D88DB6B1EA740/",
  "subject.account.id": "501",
  "subject.account.session_id": "11543",
  "subject.process.fullpath": "/System/Volumes/Preboot/Cryptexes/Incoming/OS/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/Contents/MacOS/com.apple.WebKit.Networking",
  "subject.process.hash": "UNKNOWN:A79DF6340FBD8B5831ACB371BFCA601EE04021D8",
  "subject.process.id": "11543",
  "subject.process.name": "com.apple.WebKit.Networking",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Volumes/Preboot/Cryptexes/Incoming/OS/System/Library/Frameworks/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.Networking.xpc/Contents/MacOS/",
  "time": "2023-07-24T14:56:24.168Z"
}