{
  "subject": "account",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "datafield1": "1129108",
  "datafield2": "3060",
  "datafield3": "C:\\Windows\\explorer.exe",
  "datafield4": "d:ai(d;;dclcrpcr;;;bu)(a;id;0x1200a9;;;bg)(a;id;fa;;;sy)(a;id;fa;;;ba)(a;id;0x1200a9;;;bu)",
  "event_src.category": "Operating system",
  "event_src.fqdn": "2008r2sp1-dc.ad2008r2.ru",
  "event_src.hostname": "2008r2sp1-dc",
  "event_src.id": "Microsoft-Windows-Security-Auditing",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4670_Permissions_on_object_changed",
  "importance": "medium",
  "msgid": "4670",
  "object.fullpath": "c:\\program files (x86)\\11\\new text document.txt",
  "object.name": "new text document.txt",
  "object.new_value": "d:arai(d;;dclcrpcr;;;bu)(a;id;fa;;;bg)(a;id;fa;;;sy)(a;id;fa;;;ba)(a;id;0x1200a9;;;bu)(a;id;fa;;;dg)",
  "object.path": "c:\\program files (x86)\\11\\",
  "object.property": "security descriptor",
  "object.type": "file",
  "object.value": "d:ai(d;;dclcrpcr;;;bu)(a;id;0x1200a9;;;bg)(a;id;fa;;;sy)(a;id;fa;;;ba)(a;id;0x1200a9;;;bu)",
  "subject.account.domain": "ad2008r2",
  "subject.account.id": "S-1-5-21-1743380172-4235219263-347487665-500",
  "subject.account.name": "administrator",
  "subject.account.session_id": "1129108",
  "subject.domain": "ad2008r2",
  "subject.id": "S-1-5-21-1743380172-4235219263-347487665-500",
  "subject.name": "administrator",
  "subject.process.fullpath": "C:\\Windows\\explorer.exe",
  "subject.process.id": "3060",
  "subject.process.name": "explorer.exe",
  "subject.process.path": "C:\\Windows\\",
  "time": "2015-10-27T14:19:03.149Z"
}