{
    "action": "modify",
    "category.generic": "Account",
    "category.high": "Users And Rights Management",
    "category.low": "Manipulation",
    "datafield2": "-",
    "event_src.category": "Directory service",
    "event_src.fqdn": "01566s-win16-ir.threebeesco.com",
    "event_src.hostname": "01566s-win16-ir",
    "event_src.subsys": "Security",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_4742_A_computer_account_was_changed",
    "importance": "low",
    "msgid": "4742",
    "object": "account",
    "object.account.domain": "3b",
    "object.account.id": "S-1-5-21-308926384-506822093-3341789130-35103",
    "object.account.name": "01566s-win16-ir$",
    "object.new_value": "_PasswordLastSet:9/15/2020_12:31:04_PM;",
    "object.property": "modified attributes",
    "status": "success",
    "subject": "account",
    "subject.account.domain": "nt authority",
    "subject.account.id": "S-1-5-7",
    "subject.account.name": "anonymous logon",
    "subject.account.session_id": "998",
    "time": "2020-09-15T19:31:04.688Z"
}