{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "242",
  "datafield2": "242",
  "datafield3": "4294967295",
  "datafield4": "242",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.StreamingUnzipService",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_extended_attribute_removed",
  "importance": "info",
  "msgid": "70",
  "object.fullpath": "/private/var/folders/zz/zyxvpxvq6csfxvn_n00000y800007k/T/com.apple.nsurlsessiond/CFNetworkDownload_UJ87hB.tmp",
  "object.name": "CFNetworkDownload_UJ87hB.tmp",
  "object.path": "/private/var/folders/zz/zyxvpxvq6csfxvn_n00000y800007k/T/com.apple.nsurlsessiond/",
  "object.property": "extended attribute",
  "object.type": "extended attributes",
  "object.value": "com.apple.streamingzip.incomplete_extraction",
  "subject.account.id": "242",
  "subject.account.session_id": "7073",
  "subject.process.fullpath": "/System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/XPCServices/com.apple.StreamingUnzipService.xpc/Contents/MacOS/com.apple.StreamingUnzipService",
  "subject.process.hash": "UNKNOWN:EE85FCA4D6448C7368525E7519238451E7563D37",
  "subject.process.id": "7073",
  "subject.process.name": "com.apple.StreamingUnzipService",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/XPCServices/com.apple.StreamingUnzipService.xpc/Contents/MacOS/",
  "time": "2023-07-25T07:35:39.634Z"
}