{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "f_fssubtype:0|f_bavail: 0|f_fsid: |f_files: 0|f_owner: 0|f_flags_ext: 0|f_blocks: 0|f_bfree: 0|f_ffree: 0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.umount",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_filesystem_remount",
  "importance": "info",
  "msgid": "23",
  "object.name": "vmhgfs",
  "object.new_value": "/Volumes/VMware Shared Folders",
  "object.property": "mount path",
  "object.type": "30",
  "object.value": ".host:/VMware Shared Folders",
  "subject.account.id": "0",
  "subject.account.session_id": "12622",
  "subject.process.fullpath": "/sbin/umount",
  "subject.process.hash": "UNKNOWN:884773FC941747F6D0ED13496521F90888749872",
  "subject.process.id": "13074",
  "subject.process.name": "umount",
  "subject.process.parent.id": "13072",
  "subject.process.path": "/sbin/",
  "time": "2023-07-25T07:36:36.517Z"
}