{
  "subject": "account",
  "action": "create",
  "object": "resource",
  "status": "success",
  "event_src.category": "Other",
  "event_src.hostname": "teamcity",
  "event_src.title": "teamcity",
  "event_src.vendor": "jetbrains",
  "id": "PT_JetBrains_TeamCity_syslog_Activities_User_Token_Management",
  "importance": "medium",
  "msgid": "create_restricted_token_for_user",
  "numfield3": 1695754539125,
  "object.account.fullname": "username",
  "object.account.id": "777",
  "object.account.name": "username",
  "object.id": "111-29bb-1111-bdab-22",
  "object.name": "tokenname",
  "object.property": "expiration_time",
  "object.type": "user_token",
  "object.value": "292278994-08-17 10:12:55.807",
  "subject.account.fullname": "username",
  "subject.account.id": "777",
  "subject.account.name": "username",
  "time": "2023-09-26T18:55:39.125Z"
}