{
  "subject": "account",
  "action": "remove",
  "object": "resource",
  "status": "success",
  "event_src.category": "Other",
  "event_src.hostname": "teamcity",
  "event_src.title": "teamcity",
  "event_src.vendor": "jetbrains",
  "id": "PT_JetBrains_TeamCity_syslog_Activities_User_Token_Management",
  "importance": "medium",
  "msgid": "delete_tokens_by_system",
  "numfield3": 1695809709685,
  "object.account.fullname": "Alexey Familiya",
  "object.account.id": "506",
  "object.account.name": "alFamiliya",
  "object.type": "user_token",
  "reason": "Automatically deleted expired tokens",
  "subject.account.fullname": "Alexey Familiya",
  "subject.account.id": "506",
  "subject.account.name": "alFamiliya",
  "time": "2023-09-27T10:15:09.685Z"
}