{
  "subject": "process",
  "action": "execute",
  "object": "command",
  "status": "failure",
  "category.generic": "Command",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "568",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.195",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_user_avc",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "USER_AVC",
  "object.value": "receive dbus_signal(PropertiesChanged)",
  "reason": "DENIED",
  "subject.privileges": "snap.zoom-client.zoom-client",
  "subject.process.id": "6223",
  "time": "2016-10-03T12:27:25.000Z"
}