{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "f_fssubtype:4|f_bavail: 23019439|f_fsid: |f_files: 78961405|f_owner: 501|f_flags_ext: 0|f_blocks: 78961407|f_bfree: 23019439|f_ffree: 23019439",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.diskarbitrationd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_system_unmount",
  "importance": "info",
  "msgid": "23",
  "object.name": "smbfs",
  "object.new_value": "/Volumes/Research",
  "object.property": "unmount path",
  "object.type": "31",
  "object.value": "//vsamal@192.168.163.1/e%24/Work/LOGGING/EndpointSecurityAPI/Research",
  "subject.account.id": "0",
  "subject.account.session_id": "109",
  "subject.process.fullpath": "/usr/libexec/diskarbitrationd",
  "subject.process.hash": "UNKNOWN:E5C88605D7DA2074F713218FA3603CBBC0F44367",
  "subject.process.id": "109",
  "subject.process.name": "diskarbitrationd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T16:47:25.012Z"
}