{
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "24417",
  "datafield1": "cp",
  "datafield3": "0640",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/etc/audit/audit.rules.prev",
  "object.id": "525480",
  "object.name": "audit.rules.prev",
  "object.path": "/etc/audit/",
  "object.property": "flags",
  "object.state": "w",
  "object.type": "regular_file",
  "object.value": "O_WRONLY|O_TRUNC",
  "subject.account.id": "0",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/bin/cp",
  "subject.process.id": "1891",
  "subject.process.meta": "cp /etc/audit/audit.rules /etc/audit/audit.rules.prev",
  "subject.process.name": "cp",
  "subject.process.parent.id": "1878",
  "subject.process.path": "/bin/",
  "time": "2019-04-29T15:21:32.000Z"
}