{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "28501",
  "datafield1": "tail",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_var_log_user_read",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "1000",
  "object.account.id": "1000",
  "object.fullpath": "/var/log/faillog",
  "object.id": "262922",
  "object.name": "faillog",
  "object.path": "/var/log/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "regular_file",
  "object.value": "O_RDONLY",
  "subject.account.id": "1000",
  "subject.account.privileges": "1000",
  "subject.account.session_id": "178",
  "subject.process.cwd": "/home/odmin",
  "subject.process.fullpath": "/usr/bin/tail",
  "subject.process.id": "2439",
  "subject.process.meta": "tail -n 10 /var/log/faillog",
  "subject.process.name": "tail",
  "subject.process.parent.id": "1790",
  "subject.process.path": "/usr/bin/",
  "time": "2019-04-29T16:44:53.000Z"
}