{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "25112",
  "datafield1": "man",
  "datafield3": "0700",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_root_read",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/root",
  "object.id": "1310753",
  "object.name": "root",
  "object.path": "/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "directory",
  "object.value": "O_RDONLY",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "178",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/man",
  "subject.process.id": "1971",
  "subject.process.meta": "/usr/bin/man zpool-features",
  "subject.process.name": "man",
  "subject.process.parent.id": "1943",
  "subject.process.path": "/usr/bin/",
  "time": "2019-04-29T15:24:13.000Z"
}