{
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "277862167",
  "datafield1": "tar",
  "datafield2": "teamcity",
  "datafield3": "0664",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.176.158",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "creat",
  "numfield2": 2001,
  "object.account.group": "teamcity",
  "object.account.id": "2001",
  "object.account.name": "teamcity",
  "object.fullpath": "/home/teamcity/build_disk/data/work/6a805ca40df42036/teamcity_output/../teamcity_output_package/ptms.db.av.eset.1.0.0.35786.tar.gz",
  "object.id": "1054991",
  "object.name": "ptms.db.av.eset.1.0.0.35786.tar.gz",
  "object.path": "/home/teamcity/build_disk/data/work/6a805ca40df42036/teamcity_output/../teamcity_output_package/",
  "object.property": "flags",
  "object.type": "regular_file",
  "object.value": "O_CREAT|O_WRONLY|O_TRUNC",
  "subject.account.id": "2001",
  "subject.account.name": "teamcity",
  "subject.account.privileges": "2001",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/home/teamcity/build_disk/data/work/6a805ca40df42036/teamcity_output",
  "subject.process.fullpath": "/usr/bin/tar",
  "subject.process.id": "104895",
  "subject.process.meta": "tar --use-compress-program=pigz -cvpf ../teamcity_output_package/ptms.db.av.eset.1.0.0.35786.tar.gz ReleaseManifest.json SignMan",
  "subject.process.name": "tar",
  "subject.process.parent.id": "104894",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-09T15:47:00.000Z"
}