{
  "subject": "account",
  "action": "access",
  "object": "link",
  "status": "failure",
  "category.generic": "Link",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "450095867",
  "datafield1": "nano",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.hostname": "wa-02",
  "event_src.rule": "pt_siem_lib_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/lib64/ld-linux-x86-64.so.2",
  "object.id": "655362",
  "object.name": "ld-linux-x86-64.so.2",
  "object.path": "/lib64/",
  "object.property": "flags",
  "object.state": "w",
  "object.storage.fullpath": "/lib64/ld-linux-x86-64.so.2",
  "object.storage.id": "1310723",
  "object.storage.name": "ld-linux-x86-64.so.2",
  "object.storage.path": "/lib64/",
  "object.type": "symlink",
  "object.value": "O_WRONLY|O_CREAT|O_APPEND",
  "reason": "Text file busy",
  "subject.account.id": "1000",
  "subject.account.name": "pt",
  "subject.account.privileges": "0",
  "subject.account.session_id": "597747",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/bin/nano",
  "subject.process.id": "52389",
  "subject.process.meta": "nano /lib64/ld-linux-x86-64.so.2",
  "subject.process.name": "nano",
  "subject.process.parent.id": "39211",
  "subject.process.path": "/bin/",
  "time": "2022-05-16T15:16:56.000Z"
}