{
  "subject": "account",
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "389150",
  "datafield1": "bash",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian",
  "event_src.rule": "pt_siem_etc_modify\r",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "logon_service": "pts/2",
  "msgid": "openat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/etc/init.d/T1543.002",
  "object.id": "154014",
  "object.name": "T1543.002",
  "object.path": "/etc/init.d/",
  "object.property": "flags",
  "object.state": "w",
  "object.type": "regular_file",
  "object.value": "O_WRONLY|O_CREAT|O_TRUNC",
  "subject.account.id": "1000",
  "subject.account.name": "neroot",
  "subject.account.privileges": "0",
  "subject.account.session_id": "2327",
  "subject.process.cwd": "/home/neroot",
  "subject.process.fullpath": "/usr/bin/bash",
  "subject.process.id": "19756",
  "subject.process.meta": "bash",
  "subject.process.name": "bash",
  "subject.process.parent.id": "19733",
  "subject.process.path": "/usr/bin/",
  "time": "2023-04-04T06:21:36.000Z"
}