{
  "action": "access",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "335485693",
  "datafield1": "atop",
  "event_src.category": "Operating system",
  "event_src.ip": "10.24.4.254",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "openat",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/sys/devices/system/cpu/cpu3/cpufreq/stats/time_in_state",
  "object.name": "time_in_state",
  "object.path": "/sys/devices/system/cpu/cpu3/cpufreq/stats/",
  "object.property": "flags",
  "object.state": "r",
  "object.value": "O_RDONLY",
  "reason": "No such file or directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/proc",
  "subject.process.fullpath": "/usr/bin/atop",
  "subject.process.id": "4102158",
  "subject.process.meta": "(sh)",
  "subject.process.name": "atop",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-12T16:00:01.000Z"
}