{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "846827727",
  "datafield1": "bash",
  "datafield2": "root",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.176.231",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "openat",
  "numfield2": 0,
  "object.account.group": "asolovyev",
  "object.account.id": "1001",
  "object.account.name": "asolovyev",
  "object.fullpath": "/home/asolovyev/.bash_history",
  "object.id": "399298",
  "object.name": ".bash_history",
  "object.path": "/home/asolovyev/",
  "object.property": "flags",
  "object.state": "w",
  "object.type": "regular_file",
  "object.value": "O_WRONLY|O_APPEND",
  "reason": "Permission denied",
  "subject.account.id": "1001",
  "subject.account.name": "asolovyev",
  "subject.account.privileges": "1001",
  "subject.account.session_id": "89022110",
  "subject.process.cwd": "/home/asolovyev",
  "subject.process.fullpath": "/bin/bash",
  "subject.process.id": "5939",
  "subject.process.meta": "-bash",
  "subject.process.name": "bash",
  "subject.process.parent.id": "5902",
  "subject.process.path": "/bin/",
  "time": "2022-03-11T09:50:34.000Z"
}