{
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "119639586",
  "datafield1": "(mkdir)",
  "datafield2": "root",
  "datafield3": "0700",
  "event_src.category": "Operating system",
  "event_src.ip": "192.70.198.184",
  "event_src.rule": "pt_siem_root_read",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "openat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root",
  "object.id": "1048580",
  "object.name": "root",
  "object.path": "/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "directory",
  "object.value": "O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/lib/systemd/systemd",
  "subject.process.id": "29443",
  "subject.process.meta": "(mkdir)",
  "subject.process.name": "systemd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/lib/systemd/",
  "time": "2022-06-03T12:05:09.000Z"
}