{
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "28488",
  "datafield1": "salt-minion",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_etc_read",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/etc/hosts",
  "object.id": "524592",
  "object.name": "hosts",
  "object.path": "/etc/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "regular_file",
  "object.value": "O_RDONLY|O_CLOEXEC",
  "subject.account.id": "0",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/bin/python2.7",
  "subject.process.id": "467",
  "subject.process.meta": "/usr/bin/python /usr/bin/salt-minion",
  "subject.process.name": "python2.7",
  "subject.process.parent.id": "449",
  "subject.process.path": "/usr/bin/",
  "time": "2019-04-29T16:44:52.000Z"
}