{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "778582",
  "datafield1": "sar",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.fqdn": "hostname.local",
  "event_src.hostname": "hostname",
  "event_src.rule": "pt_siem_var_log_user_read",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "msgid": "open",
  "numfield2": 0,
  "object.account.group": "oinstall",
  "object.account.id": "1001",
  "object.account.name": "oracle",
  "object.fullpath": "/var/log/sa/sa10",
  "object.id": "50805147",
  "object.name": "sa10",
  "object.path": "/var/log/sa/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "regular_file",
  "object.value": "O_RDONLY",
  "subject.account.id": "1000",
  "subject.account.name": "codansible",
  "subject.account.privileges": "1001",
  "subject.account.session_id": "130",
  "subject.process.cwd": "/home/user/file",
  "subject.process.fullpath": "/usr/bin/sar",
  "subject.process.id": "5970",
  "subject.process.meta": "sar -B",
  "subject.process.name": "sar",
  "subject.process.parent.id": "5961",
  "subject.process.path": "/usr/bin/",
  "time": "2020-06-10T13:43:05.000Z"
}