{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "3103253",
  "datafield1": "fdisk",
  "datafield2": "root",
  "datafield3": "0660",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "parsec-f",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "openat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/dev/sr0",
  "object.id": "153",
  "object.name": "sr0",
  "object.path": "/dev/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "block_device",
  "object.value": "O_RDONLY|O_CLOEXEC",
  "reason": "No medium found",
  "subject.account.id": "2002",
  "subject.account.name": "audit",
  "subject.account.privileges": "0",
  "subject.account.session_id": "2913",
  "subject.process.cwd": "/home/audit",
  "subject.process.fullpath": "/usr/sbin/fdisk",
  "subject.process.id": "29161",
  "subject.process.meta": "/sbin/fdisk -l",
  "subject.process.name": "fdisk",
  "subject.process.parent.id": "29160",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-09-22T07:08:33.000Z"
}