{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "861085",
  "datafield1": "chattr",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_file_operations",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/7",
  "msgid": "openat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/toor",
  "object.id": "420272",
  "object.name": "toor",
  "object.path": "/root/",
  "object.property": "flags",
  "object.state": "r",
  "object.type": "executable_file",
  "object.value": "O_RDONLY|O_NONBLOCK",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "11",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/chattr",
  "subject.process.id": "48195",
  "subject.process.meta": "chattr +a toor",
  "subject.process.name": "chattr",
  "subject.process.parent.id": "3668",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-20T08:29:13.000Z"
}