{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "0",
  "datafield12": "1",
  "datafield13": "262146",
  "datafield14": "3",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.rtcreportingd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_memory_to_file_mapping",
  "importance": "info",
  "msgid": "20",
  "object.fullpath": "/private/var/root/Library/Caches/com.apple.rtcreporting/storebags/nimbus.plist",
  "object.name": "nimbus.plist",
  "object.path": "/private/var/root/Library/Caches/com.apple.rtcreporting/storebags/",
  "subject.account.id": "0",
  "subject.account.session_id": "283",
  "subject.process.fullpath": "/usr/libexec/rtcreportingd",
  "subject.process.hash": "UNKNOWN:8C4E85CC169AEA235F3AA07AAC6C19F7A0CE3CFC",
  "subject.process.id": "283",
  "subject.process.name": "rtcreportingd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T11:44:36.775Z"
}