{
  "subject": "account",
  "action": "grant",
  "object": "db_object",
  "status": "success",
  "datafield1": "grant VIEW DEFINITION on CERTIFICATE::Shipping05 to bobby",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "AdventureWorks2012",
  "datafield4": "G",
  "datafield5": "CR",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_permissions_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.account.name": "bobby",
  "object.name": "Shipping05",
  "object.property": "target username",
  "object.query": "grant VIEW DEFINITION on CERTIFICATE::Shipping05 to bobby",
  "object.type": "certificate",
  "object.value": "bobby",
  "time": "2015-09-23T07:45:55Z"
}