{
  "action": "info",
  "object": "file_object",
  "status": "ongoing",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.mds",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_filesystem_or_volume_searching",
  "importance": "info",
  "msgid": "89",
  "object.property": "attributes list",
  "object.storage.fullpath": "/System/Volumes/Data",
  "object.storage.name": "Data",
  "object.storage.path": "/System/Volumes/",
  "object.value": "bitmapcount:5|fileattr:0|dirattr:0|forkattr:0|volattr:0|commonattr:32769",
  "subject.account.id": "0",
  "subject.account.session_id": "106",
  "subject.process.fullpath": "/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds",
  "subject.process.hash": "UNKNOWN:0287DF5FFF3895D7BF84AD67E2B6FA3AF2992AF7",
  "subject.process.id": "106",
  "subject.process.name": "mds",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/",
  "time": "2023-07-25T09:22:30.209Z"
}