{
  "action": "info",
  "object": "file_object",
  "status": "success",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.endpointsecurityd",
  "datafield8": "570522369",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_path_lookup",
  "importance": "info",
  "msgid": "43",
  "object.fullpath": "usr/bin/eslogger",
  "object.name": "eslogger",
  "object.property": "source directory",
  "object.value": "usr/bin/eslogger",
  "subject.account.id": "0",
  "subject.account.session_id": "91",
  "subject.process.fullpath": "/usr/libexec/endpointsecurityd",
  "subject.process.hash": "UNKNOWN:FED73904B0953E2EEBD83E460798B4F360CF8506",
  "subject.process.id": "91",
  "subject.process.name": "endpointsecurityd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T12:04:21.752Z"
}