{
  "subject": "account",
  "action": "connect",
  "object": "database",
  "status": "failure",
  "datafield2": "DESKTOP-I2RR0AI",
  "datafield4": "LGIF",
  "datafield5": "LX",
  "datafield8": "SQLCMD",
  "datafield9": "<action_info xmlns=\"http://schemas.microsoft.com/sqlserver/2008/sqlaudit_data\"><pooled_connection>0</pooled_connection><error>0x00004813</error><state>1</state><address>127.0.0.1</address></action_info>",
  "dst.hostname": "desktop-i2rr0ai",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-i2rr0ai",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_connection",
  "importance": "high",
  "msgid": "33205",
  "reason": "Login failed for user 'DESKTOP-I2RR0AI\\WindowsMan'. Only administrators may connect at this time. [CLIENT: 127.0.0.1]",
  "src.ip": "127.0.0.1",
  "subject.account.domain": "desktop-i2rr0ai",
  "subject.account.name": "windowsman",
  "subject.domain": "desktop-i2rr0ai",
  "subject.name": "windowsman",
  "time": "2021-07-02T12:03:01Z"
}