{
  "subject": "account",
  "action": "modify",
  "object": "db_object",
  "status": "success",
  "datafield1": "ALTER SERVER AUDIT SPECIFICATION [ForChangeSpec] DROP (BACKUP_RESTORE_GROUP), DROP (BROKER_LOGIN_GROUP)",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "AL",
  "datafield5": "SA",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_object_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "ForChangeSpec",
  "object.query": "ALTER SERVER AUDIT SPECIFICATION [ForChangeSpec] DROP (BACKUP_RESTORE_GROUP), DROP (BROKER_LOGIN_GROUP)",
  "object.type": "server audit specification",
  "subject.account.id": "51dd4b885506ac48827997ba5521b176",
  "subject.account.name": "siemagent",
  "subject.id": "51dd4b885506ac48827997ba5521b176",
  "subject.name": "siemagent",
  "time": "2020-02-05T11:16:47Z"
}