{
  "subject": "account",
  "action": "disable",
  "object": "db_object",
  "status": "success",
  "datafield1": "ALTER SERVER AUDIT SPECIFICATION [MP_SIEM_Audit_Spec_to_file] WITH (STATE = OFF)",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "master",
  "datafield4": "AL",
  "datafield5": "SA",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_object_operation",
  "importance": "high",
  "msgid": "33205",
  "object.name": "MP_SIEM_Audit_Spec_to_file",
  "object.query": "ALTER SERVER AUDIT SPECIFICATION [MP_SIEM_Audit_Spec_to_file] WITH (STATE = OFF)",
  "object.type": "server audit specification",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T07:52:28Z"
}