{
  "subject": "account",
  "action": "disable",
  "object": "db_object",
  "status": "success",
  "datafield1": "ALTER SERVER AUDIT [Sec Audit] WITH (STATE = OFF)",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "AL",
  "datafield5": "A",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_object_operation",
  "importance": "high",
  "msgid": "33205",
  "object.name": "Sec Audit",
  "object.query": "ALTER SERVER AUDIT [Sec Audit] WITH (STATE = OFF)",
  "object.type": "audit",
  "subject.account.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.account.name": "analysis",
  "subject.id": "5c9dc62711b2c84695fc5132e3a852db",
  "subject.name": "analysis",
  "time": "2020-01-31T13:23:38Z"
}