{
  "subject": "account",
  "action": "modify",
  "object": "db_object",
  "status": "failure",
  "datafield1": "ALTER SERVER AUDIT SPECIFICATION [Spec01] DROP (BROKER_LOGIN_GROUP)",
  "datafield2": "DESKTOP-GB13G7P",
  "datafield3": "master",
  "datafield4": "AL",
  "datafield5": "SA",
  "event_src.category": "Database server",
  "event_src.hostname": "desktop-gb13g7p",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_object_operation",
  "importance": "medium",
  "msgid": "33205",
  "object.name": "spec01",
  "object.query": "ALTER SERVER AUDIT SPECIFICATION [Spec01] DROP (BROKER_LOGIN_GROUP)",
  "object.type": "server audit specification",
  "subject.account.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.account.name": "hackerlooser",
  "subject.id": "19681a2750a1c34585ebc9f68dcda43c",
  "subject.name": "hackerlooser",
  "time": "2020-03-05T10:05:24Z"
}