{
    "action": "modify",
    "datafield1": "2558525824",
    "event_src.category": "Operating system",
    "event_src.fqdn": "win10-work.stand2008.local",
    "event_src.hostname": "win10-work",
    "event_src.id": "b675ec37-bdb6-4648-bc92-f3fdc74d3ca2",
    "event_src.subsys": "Microsoft-Windows-Kernel-EventTracing/Analytic",
    "event_src.title": "Microsoft-Windows-Kernel-EventTracing",
    "event_src.vendor": "microsoft",
    "id": "Microsoft_Windows_eventlog_Common_EventTracing_17_The security_descriptor_for_session_has_been_updated",
    "importance": "info",
    "msgid": "17",
    "object": "logging",
    "object.id": "d2112be4-cd15-5a9c-e38f-080a207e08d5",
    "object.name": "eventlog-system",
    "object.property": "security descriptor",
    "object.state": "updated",
    "object.type": "session",
    "status": "success",
    "time": "2024-05-02T15:59:20.641Z"
}