{
  "subject": "process",
  "action": "create",
  "object": "resource",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.backgroundtaskmanagementd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_btm_launch_item_add",
  "importance": "info",
  "msgid": "124",
  "object.fullpath": "/System/Applications/App%20Store.app",
  "object.name": "App%20Store.app",
  "object.path": "/System/Applications/",
  "object.type": "autoload item",
  "subject.account.id": "0",
  "subject.account.session_id": "279",
  "subject.process.fullpath": "/System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/Resources/backgroundtaskmanagementd",
  "subject.process.hash": "UNKNOWN:0D816E397530D5FDF31299AA6893DEE710C9F101",
  "subject.process.id": "279",
  "subject.process.name": "backgroundtaskmanagementd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/Resources/",
  "time": "2023-07-25T07:58:05.134Z"
}