{
  "action": "modify",
  "object": "configuration",
  "status": "success",
  "chain_id": "12926077",
  "datafield1": "PLUGIN[timex]",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.10.10",
  "event_src.rule": "pt_siem_api_time",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_time_change",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "adjtimex",
  "object.account.group": "netdata",
  "object.account.id": "110",
  "object.account.name": "netdata",
  "object.state": "system_time_change",
  "subject.account.id": "110",
  "subject.account.name": "netdata",
  "subject.account.privileges": "110",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/netdata",
  "subject.process.id": "30084",
  "subject.process.meta": "/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D",
  "subject.process.name": "netdata",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-05-21T12:22:03.000Z"
}