{
  "subject": "account",
  "action": "modify",
  "object": "configuration",
  "status": "success",
  "chain_id": "26930",
  "datafield1": "date",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_api_time",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_time_change",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "clock_settime",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.state": "system_time_change",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "180",
  "subject.process.fullpath": "/bin/date",
  "subject.process.id": "2195",
  "subject.process.meta": "date -s 29 apr 2019 19:10:30",
  "subject.process.name": "date",
  "subject.process.parent.id": "2096",
  "subject.process.path": "/bin/",
  "time": "2019-04-29T16:10:25.000Z"
}