{
  "action": "open",
  "object": "session",
  "status": "success",
  "category.generic": "Operating System",
  "category.high": "Access Management",
  "category.low": "Communication",
  "datafield1": "501",
  "datafield11": "H7V7XYVQ7D",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "iTermServer",
  "datafield8": "570503953",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_grant_pseudoterminal_device_to_user",
  "importance": "info",
  "msgid": "83",
  "object.version": "251658240",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/Users/user/Library/Application Support/iTerm2/iTermServer-3.4.19",
  "subject.process.hash": "UNKNOWN:5D8546B70A69B0B3FCA414875FFB79A8B435ACA8",
  "subject.process.id": "12794",
  "subject.process.name": "iTermServer-3.4.19",
  "subject.process.parent.id": "12720",
  "subject.process.path": "/Users/user/Library/Application Support/iTerm2/",
  "time": "2023-07-25T07:35:26.307Z"
}