{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "501",
  "datafield10": "6438",
  "datafield13": "6438",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.debugserver",
  "datafield8": "570444289",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_attempt_to_attach_to_process",
  "importance": "info",
  "msgid": "96",
  "object.account.session_id": "6290",
  "object.fullpath": "/Users/user/Library/Developer/Xcode/DerivedData/PackageExtractor-edajpfxtmzucptgdcfxdotlxzhds/Build/Products/Release/PackageExtractor",
  "object.name": "PackageExtractor",
  "object.path": "/Users/user/Library/Developer/Xcode/DerivedData/PackageExtractor-edajpfxtmzucptgdcfxdotlxzhds/Build/Products/Release/",
  "subject.account.id": "501",
  "subject.account.session_id": "6290",
  "subject.process.fullpath": "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver",
  "subject.process.hash": "UNKNOWN:CCE5B1D4C715EC8E0B9CF24307E6AD5EF2CC42EC",
  "subject.process.id": "6438",
  "subject.process.name": "debugserver",
  "subject.process.parent.id": "6432",
  "subject.process.path": "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/",
  "time": "2023-07-25T12:01:23.142Z"
}