{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "88",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.WindowServer",
  "datafield8": "570522369",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_effective_user_id_setting",
  "importance": "info",
  "msgid": "105",
  "object.account.id": "0",
  "object.account.session_id": "147",
  "object.process.fullpath": "/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer",
  "object.process.id": "147",
  "object.process.name": "WindowServer",
  "object.process.parent.id": "1",
  "object.process.path": "/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/",
  "object.property": "effective user id",
  "object.value": "88",
  "subject.account.id": "0",
  "subject.account.session_id": "147",
  "subject.process.fullpath": "/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer",
  "subject.process.hash": "UNKNOWN:CC2871EC4227CFB961A7CB519B4C911C143E76C6",
  "subject.process.id": "147",
  "subject.process.name": "WindowServer",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/",
  "time": "2023-07-24T12:12:44.862Z"
}