{
  "subject": "process",
  "action": "create",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield10": "8009",
  "datafield12": "100005",
  "datafield13": "501",
  "datafield14": "501",
  "datafield15": "20",
  "datafield16": "501",
  "datafield17": "20",
  "datafield18": "8012",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.xargs",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_process_forking",
  "importance": "info",
  "msgid": "11",
  "object.process.fullpath": "/usr/bin/xargs",
  "object.process.name": "xargs",
  "object.process.path": "/usr/bin/",
  "subject.account.id": "501",
  "subject.account.session_id": "5451",
  "subject.process.fullpath": "/usr/bin/xargs",
  "subject.process.hash": "UNKNOWN:35E2582A2D60BAB3AB12D871ABE69FF8AE1FD96D",
  "subject.process.id": "8009",
  "subject.process.name": "xargs",
  "subject.process.parent.id": "5452",
  "subject.process.path": "/usr/bin/",
  "time": "2023-07-24T12:12:42.615Z"
}