{
  "subject": "account",
  "action": "login",
  "object": "system",
  "status": "failure",
  "category.generic": "Operating System",
  "category.high": "Access Management",
  "category.low": "Communication",
  "datafield1": "0",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.login",
  "datafield8": "570522385",
  "datafield9": "/dev/ttys003",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_user_login",
  "importance": "info",
  "msgid": "122",
  "reason": "Login incorrect",
  "subject.account.name": "\u001b[A\u001b[A",
  "subject.process.fullpath": "/usr/bin/login",
  "subject.process.hash": "UNKNOWN:3C84630D5F8E58DE05D0F606F618A2978A5730E0",
  "subject.process.id": "3287",
  "subject.process.name": "login",
  "subject.process.parent.id": "3243",
  "subject.process.path": "/usr/bin/",
  "time": "2023-07-25T09:19:00.248Z"
}