{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "0",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.loginwindow",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_setting_effective_and_real_process_group_id",
  "importance": "info",
  "msgid": "107",
  "object.account.id": "0",
  "object.account.session_id": "12588",
  "object.id": "0",
  "object.process.fullpath": "/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow",
  "object.process.id": "12588",
  "object.process.name": "loginwindow",
  "object.process.parent.id": "1",
  "object.process.path": "/System/Library/CoreServices/loginwindow.app/Contents/MacOS/",
  "object.property": "effective group id",
  "object.value": "501",
  "subject.account.id": "0",
  "subject.account.session_id": "12588",
  "subject.process.fullpath": "/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow",
  "subject.process.hash": "UNKNOWN:837B9EC93F61380F4F07AB23454ACF1E5EE8F81A",
  "subject.process.id": "12588",
  "subject.process.name": "loginwindow",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/CoreServices/loginwindow.app/Contents/MacOS/",
  "time": "2023-07-25T07:35:24.089Z"
}