{
  "subject": "account",
  "action": "login",
  "object": "system",
  "status": "ongoing",
  "category.generic": "Operating System",
  "category.high": "Access Management",
  "category.low": "Communication",
  "chain_id": "1951",
  "event_src.category": "Operating system",
  "event_src.ip": "10.1.76.35",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_login",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "LOGIN",
  "object.new_value": "6",
  "object.process.fullpath": "/usr/lib/systemd/systemd",
  "object.process.id": "2034",
  "object.process.meta": "(systemd)",
  "object.process.name": "systemd",
  "object.process.parent.id": "1",
  "object.process.path": "/usr/lib/systemd/",
  "object.property": "session_id",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.session_id": "6",
  "subject.state": "changed-login-id-to",
  "time": "2020-08-25T10:56:31.000Z"
}