{
  "subject": "process",
  "action": "modify",
  "object": "resource",
  "status": "success",
  "datafield1": "501",
  "datafield10": "24889401016320",
  "datafield11": "UBF8T346G9",
  "datafield12": "3",
  "datafield13": "262144",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "com.github.Electron.helper",
  "datafield8": "570491649",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_memory_mapped_pages_protection_changed",
  "importance": "info",
  "msgid": "21",
  "object.type": "memory-mapped page",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "subject.process.hash": "UNKNOWN:C62A1E45726AD1393A6386FE42D662269BB427F8",
  "subject.process.id": "6270",
  "subject.process.name": "Code Helper (Plugin)",
  "subject.process.parent.id": "6248",
  "subject.process.path": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/",
  "time": "2023-07-24T12:12:23.201Z"
}