{
  "subject": "process",
  "action": "read",
  "object": "resource",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield11": "EG7KH642X6",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "com.vmware.vmware-tools-daemon",
  "datafield8": "570490881",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_symbolic_link_read",
  "importance": "info",
  "msgid": "39",
  "object.fullpath": "/etc",
  "object.name": "etc",
  "object.path": "/",
  "object.type": "symbolic link",
  "subject.account.id": "0",
  "subject.account.session_id": "296",
  "subject.process.fullpath": "/Library/Application Support/VMware Tools/vmware-tools-daemon",
  "subject.process.hash": "UNKNOWN:9206F2D9BEE895411FB540732374AA041948850F",
  "subject.process.id": "296",
  "subject.process.name": "vmware-tools-daemon",
  "subject.process.parent.id": "1",
  "subject.process.path": "/Library/Application Support/VMware Tools/",
  "time": "2023-07-24T12:05:43.001Z"
}