{
  "subject": "process",
  "action": "assign",
  "object": "socket",
  "status": "success",
  "category.generic": "Socket",
  "category.high": "Network Interaction Management",
  "category.low": "Manipulation",
  "datafield1": "501",
  "datafield2": "20",
  "datafield3": "501",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.Safari",
  "datafield8": "570522369",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_socket_connection",
  "importance": "info",
  "msgid": "78",
  "numfield1": 2,
  "numfield2": 1,
  "object.fullpath": "/private/var/run/syslog",
  "object.name": "syslog",
  "object.path": "/private/var/run/",
  "object.property": "communications domain of the socket",
  "object.type": "datagram socket",
  "object.value": "local to host (pipes)",
  "protocol": "0",
  "subject.account.id": "501",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/Contents/MacOS/Safari",
  "subject.process.hash": "UNKNOWN:7D4A1772EDDC8AF8267F219805A9C44005DF201E",
  "subject.process.id": "11541",
  "subject.process.name": "Safari",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/Contents/MacOS/",
  "time": "2023-07-24T14:56:08.772Z"
}