{
  "subject": "account",
  "action": "login",
  "object": "system",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "Users",
  "datafield11": "opendirectory",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.opendirectoryd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_authentication",
  "importance": "info",
  "msgid": "authentication:111",
  "object.fullpath": "/Local/Default",
  "object.name": "Default",
  "object.path": "/Local/",
  "object.process.path": "/usr/sbin/sshd",
  "object.type": "node",
  "subject.account.id": "0",
  "subject.account.session_id": "117",
  "subject.process.fullpath": "/usr/libexec/opendirectoryd",
  "subject.process.hash": "UNKNOWN:6CB9BB6C7F4636773ACD2009F0FC9FB5628AE98B",
  "subject.process.id": "117",
  "subject.process.name": "opendirectoryd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T16:46:39.706Z"
}