{
  "subject": "process",
  "action": "assign",
  "object": "socket",
  "status": "success",
  "category.generic": "Socket",
  "category.high": "Network Interaction Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.xpc.launchd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_socket_binding_to_path",
  "importance": "info",
  "msgid": "76",
  "object.name": "Listeners",
  "object.path": "/private/tmp/com.apple.launchd.XJuMro2DpG",
  "object.property": "mode of the socket file",
  "object.value": "49645",
  "subject.account.id": "0",
  "subject.account.session_id": "1",
  "subject.process.fullpath": "/sbin/launchd",
  "subject.process.hash": "UNKNOWN:F7618A048AA74CE1EA04F2AC56D3854B5E824548",
  "subject.process.id": "1",
  "subject.process.name": "launchd",
  "subject.process.parent.id": "0",
  "subject.process.path": "/sbin/",
  "time": "2023-07-25T07:35:24.177Z"
}