{
  "subject": "account",
  "action": "access",
  "object": "resource",
  "status": "failure",
  "datafield1": "997",
  "datafield2": "c:\\windows\\system32\\lsass.exe",
  "event_src.category": "Operating system",
  "event_src.fqdn": "comp1.domainname.ru",
  "event_src.hostname": "comp1",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4674_Operation_was_attempted_on_a_privileged_object",
  "importance": "info",
  "msgid": "4674",
  "object.group": "LSA",
  "object.property": "privilege list",
  "object.value": "SeSecurityPrivilege",
  "subject.account.domain": "nt authority",
  "subject.account.id": "S-1-5-19",
  "subject.account.name": "local service",
  "subject.account.session_id": "997",
  "subject.domain": "nt authority",
  "subject.id": "S-1-5-19",
  "subject.name": "local service",
  "subject.process.fullpath": "c:\\windows\\system32\\lsass.exe",
  "subject.process.name": "lsass.exe",
  "subject.process.path": "c:\\windows\\system32\\",
  "time": "2015-07-17T21:01:52Z"
}