{
  "subject": "account",
  "action": "access",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "537762655",
  "datafield2": "c:\\0apps\\sys\\far2\\far.exe",
  "event_src.category": "Operating system",
  "event_src.fqdn": "oo.py.ru",
  "event_src.hostname": "oo",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4674_Operation_was_attempted_on_a_privileged_object",
  "importance": "info",
  "msgid": "4674",
  "object.fullpath": "c:\\0apps\\dev\\vscode",
  "object.group": "Security",
  "object.name": "vscode",
  "object.path": "c:\\0apps\\dev\\",
  "object.property": "privilege list",
  "object.value": "SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPrivilege",
  "subject.account.domain": "py",
  "subject.account.id": "S-1-5-21-1023000730-727829927-3985050192-39007",
  "subject.account.name": "oo",
  "subject.account.session_id": "537762655",
  "subject.domain": "py",
  "subject.id": "S-1-5-21-1023000730-727829927-3985050192-39007",
  "subject.name": "oo",
  "subject.process.fullpath": "c:\\0apps\\sys\\far2\\far.exe",
  "subject.process.name": "far.exe",
  "subject.process.path": "c:\\0apps\\sys\\far2\\",
  "time": "2022-06-24T09:04:29Z"
}