{
  "subject": "account",
  "action": "access",
  "object": "reg_object",
  "status": "success",
  "category.generic": "Registry Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "171969446",
  "datafield2": "c:\\windows\\system32\\wbem\\wmiprvse.exe",
  "event_src.category": "Operating system",
  "event_src.fqdn": "wed-02.id.py.ru",
  "event_src.hostname": "wed-02",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4674_Operation_was_attempted_on_a_privileged_object",
  "importance": "info",
  "msgid": "4674",
  "object.fullpath": "\\registry\\machine\\software\\microsoft\\windows nt\\currentversion\\perflib",
  "object.group": "Security",
  "object.path": "\\registry\\machine\\software\\microsoft\\windows nt\\currentversion\\perflib",
  "object.property": "privilege list",
  "object.value": "SeSecurityPrivilege",
  "subject.account.domain": "id",
  "subject.account.id": "S-1-5-21-1755400539-2578027476-4120372289-1619",
  "subject.account.name": "ident",
  "subject.account.session_id": "171969446",
  "subject.domain": "id",
  "subject.id": "S-1-5-21-1755400539-2578027476-4120372289-1619",
  "subject.name": "ident",
  "subject.process.fullpath": "c:\\windows\\system32\\wbem\\wmiprvse.exe",
  "subject.process.name": "wmiprvse.exe",
  "subject.process.path": "c:\\windows\\system32\\wbem\\",
  "time": "2022-06-24T09:26:49Z"
}