{
  "subject": "account",
  "action": "create",
  "object": "account",
  "status": "success",
  "category.generic": "Account",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "datafield1": "CREATE LOGIN login2 WITH PASSWORD = '******';",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "master",
  "datafield4": "CR",
  "datafield5": "SL",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_account_operation",
  "importance": "high",
  "msgid": "33205",
  "object.account.name": "login2",
  "object.query": "CREATE LOGIN login2 WITH PASSWORD = '******';",
  "object.type": "server login",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T08:10:29Z"
}