{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "122424",
  "datafield1": " bash",
  "datafield2": "mpuser",
  "datafield3": "0755",
  "datafield4": "/tmp/ bash",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "execve",
  "numfield2": 1000,
  "object.account.group": "mpuser",
  "object.account.id": "1000",
  "object.account.name": "mpuser",
  "object.process.cmdline": "/tmp/ bash --version",
  "object.process.cwd": "/home/mpuser",
  "object.process.fullpath": "/tmp/ bash",
  "object.process.id": "21194",
  "object.process.meta": "/tmp/ bash --version",
  "object.process.name": "bash",
  "object.process.parent.id": "19927",
  "object.process.path": "/tmp/ ",
  "subject.account.id": "1000",
  "subject.account.name": "mpuser",
  "subject.account.privileges": "1000",
  "subject.account.session_id": "5",
  "time": "2020-03-19T11:39:25.000Z"
}