{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "1912916365",
  "datafield1": "rq",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/usr/local/bin/python3.8",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.9",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "/usr/local/bin/python /usr/local/bin/rq worker -u redis://redis:6380 --with-scheduler",
  "object.process.cwd": "/app",
  "object.process.fullpath": "/usr/local/bin/rq",
  "object.process.id": "49072",
  "object.process.meta": "runc init",
  "object.process.name": "rq",
  "object.process.parent.id": "49034",
  "object.process.path": "/usr/local/bin/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2022-05-08T01:10:16.000Z"
}