{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "398908980",
  "datafield1": "update-motd-reb",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/bin/dash",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.10.9",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "/bin/sh -e /usr/lib/update-notifier/update-motd-reboot-required",
  "object.process.cwd": "/",
  "object.process.fullpath": "/usr/lib/update-notifier/update-motd-reboot-required",
  "object.process.id": "59503",
  "object.process.meta": "/bin/sh /etc/update-motd.d/98-reboot-required",
  "object.process.name": "update-motd-reboot-required",
  "object.process.parent.id": "59444",
  "object.process.path": "/usr/lib/update-notifier/",
  "subject.account.id": "998",
  "subject.account.name": "git",
  "subject.account.privileges": "0",
  "subject.account.session_id": "2753261",
  "time": "2022-05-05T17:31:46.000Z"
}