{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "1590",
  "datafield1": "run",
  "datafield2": "root",
  "datafield3": "0775",
  "datafield4": "/usr/bin/bash",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.49.19",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "/bin/bash /usr/bin/with-contenv bash /etc/s6-overlay/s6-rc.d/init-mods-package-install/run",
  "object.process.cwd": "/run/s6-rc:s6-rc-init:kJhlFp/servicedirs/s6rc-oneshot-runner",
  "object.process.fullpath": "/etc/s6-overlay/s6-rc.d/init-mods-package-install/run",
  "object.process.id": "1695",
  "object.process.meta": "/package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. -- up 6",
  "object.process.name": "run",
  "object.process.parent.id": "1694",
  "object.process.path": "/etc/s6-overlay/s6-rc.d/init-mods-package-install/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2023-05-14T23:31:49.000Z"
}