{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "2067919677",
  "datafield1": "4",
  "datafield2": "root",
  "datafield3": "0777",
  "datafield4": "/memfd:runc_cloned:/proc/self/exe (deleted)",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.192.146",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execveat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "docker-runc init",
  "object.process.cwd": "/var/lib/docker/overlay2/d47cd34fae76f9cec891da11f01f42c58f1fae1c2abf8d14d8f13a5efc33279c/merged",
  "object.process.id": "14139",
  "object.process.meta": "docker-runc init",
  "object.process.parent.id": "14120",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2022-05-11T16:40:37.000Z"
}