{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "28483",
  "datafield1": "tail",
  "datafield3": "0755",
  "datafield4": "/usr/bin/tail",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "1000",
  "object.account.id": "1000",
  "object.process.cmdline": "tail -n 10 /var/log/debug",
  "object.process.cwd": "/home/odmin",
  "object.process.fullpath": "/usr/bin/tail",
  "object.process.id": "2436",
  "object.process.meta": "tail -n 10 /var/log/debug",
  "object.process.name": "tail",
  "object.process.parent.id": "1790",
  "object.process.path": "/usr/bin/",
  "subject.account.id": "1000",
  "subject.account.privileges": "1000",
  "subject.account.session_id": "178",
  "time": "2019-04-29T16:44:45.000Z"
}