{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "529656",
  "datafield1": "ping",
  "datafield4": "/usr/bin/ping",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "msgid": "execve",
  "object.account.group": "zabbix",
  "object.account.id": "998",
  "object.account.name": "zabbix",
  "object.process.id": "10931",
  "object.process.meta": "ping -c 1 -w 1 10.163.168.129",
  "object.process.parent.id": "10922",
  "subject.account.id": "998",
  "subject.account.name": "zabbix",
  "subject.account.privileges": "998",
  "subject.account.session_id": "4294967295",
  "time": "2022-04-29T01:16:24.000Z"
}