{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "29447",
  "datafield1": "mandb",
  "datafield3": "0755",
  "datafield4": "/usr/bin/mandb",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_execve_daemon",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "logon_service": "pts/2",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "12",
  "object.account.id": "6",
  "object.process.cmdline": "/usr/bin/mandb -pq",
  "object.process.cwd": "/",
  "object.process.fullpath": "/usr/bin/mandb",
  "object.process.id": "2571",
  "object.process.meta": "perl -e @pwd = getpwnam(\"man\"); $) = $( = $pwd[3]; $> = $< = $pwd[2];\n\t     exec \"/usr/bin/mandb\", @ARGV -- -pq",
  "object.process.name": "mandb",
  "object.process.parent.id": "2570",
  "object.process.path": "/usr/bin/",
  "subject.account.id": "1000",
  "subject.account.privileges": "6",
  "subject.account.session_id": "178",
  "time": "2019-04-29T16:51:06.000Z"
}