{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "failure",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "27436",
  "datafield1": "dpkg",
  "datafield4": "/usr/bin/dpkg",
  "datafield5": "/usr/sbin/rm",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "logon_service": "pts/2",
  "msgid": "execve",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.process.cwd": "/",
  "object.process.fullpath": "/usr/sbin/rm",
  "object.process.id": "2253",
  "object.process.meta": "/usr/bin/dpkg --status-fd 17 --no-triggers --unpack --auto-deconfigure /var/cache/apt/archives/acl_2.2.52-3+b1_amd64.deb",
  "object.process.name": "rm",
  "object.process.parent.id": "2243",
  "object.process.path": "/usr/sbin/",
  "reason": "No such file or directory",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "180",
  "time": "2019-04-29T16:16:01.000Z"
}