{
  "action": "start",
  "object": "process",
  "status": "failure",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "18900216",
  "datafield1": "kube-controller",
  "datafield2": "root",
  "datafield3": "0550",
  "datafield4": "/usr/local/bin/kube-controller-manager",
  "datafield5": "/lib64/ld-linux-x86-64.so.2",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.52.199",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cwd": "/",
  "object.process.fullpath": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds",
  "object.process.id": "2883485",
  "object.process.meta": "kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authori",
  "object.process.name": "uds",
  "object.process.parent.id": "2868169",
  "object.process.path": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/",
  "reason": "No such file or directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2023-05-13T12:13:23.000Z"
}