{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "2024906218",
  "datafield1": "5",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.9",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "runc init",
  "object.process.cwd": "/var/lib/docker/overlay2/3f822c5e33ae800afc5b4dee254b611b5c0a4e243e4328020819960f356638e7/merged",
  "object.process.fullpath": "/proc/self/fd/5",
  "object.process.id": "36863",
  "object.process.meta": "runc init",
  "object.process.name": "5",
  "object.process.parent.id": "36855",
  "object.process.path": "/proc/self/fd/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2022-05-11T14:22:58.000Z"
}