{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "14673989",
  "datafield1": "debian-sa1",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/usr/bin/dash",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.48.157",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "/bin/sh /usr/lib/sysstat/debian-sa1 1 1",
  "object.process.cwd": "/root",
  "object.process.fullpath": "/usr/lib/sysstat/debian-sa1",
  "object.process.id": "2286097",
  "object.process.meta": "/bin/sh /usr/lib/sysstat/debian-sa1 1 1",
  "object.process.name": "debian-sa1",
  "object.process.parent.id": "2286095",
  "object.process.path": "/usr/lib/sysstat/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "13134",
  "time": "2022-05-17T08:15:01.000Z"
}