{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "2701",
  "datafield1": "ld-2.31.so",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/usr/lib/x86_64-linux-gnu/ld-2.31.so",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "./ld-2.31.so /sbin/ip addr",
  "object.process.cwd": "/usr/lib/x86_64-linux-gnu",
  "object.process.fullpath": "/usr/lib/x86_64-linux-gnu/ld-2.31.so",
  "object.process.id": "13677",
  "object.process.meta": "./ld-2.31.so /sbin/ip addr",
  "object.process.name": "ld-2.31.so",
  "object.process.parent.id": "5912",
  "object.process.path": "/usr/lib/x86_64-linux-gnu/",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4",
  "time": "2022-06-06T14:27:14.000Z"
}