{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "665060",
  "datafield1": "console",
  "datafield2": "unknown(990)",
  "datafield3": "0775",
  "datafield4": "/usr/bin/coreutils",
  "event_src.category": "Operating system",
  "event_src.hostname": "hostname",
  "event_src.rule": "pt_siem_execve_daemon",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "msgid": "execve",
  "numfield2": 990,
  "object.account.group": "unknown(986)",
  "object.account.id": "990",
  "object.account.name": "unknown(990)",
  "object.process.cmdline": "/usr/bin/coreutils --coreutils-prog-shebang=env /usr/bin/env php bin/console s:b:rank",
  "object.process.cwd": "/app",
  "object.process.fullpath": "/app/bin/console",
  "object.process.id": "1095674",
  "object.process.meta": "/bin/sh -c bin/console s:b:rank",
  "object.process.name": "console",
  "object.process.parent.id": "58365",
  "object.process.path": "/app/bin/",
  "subject.account.id": "990",
  "subject.account.name": "unknown(990)",
  "subject.account.privileges": "990",
  "subject.account.session_id": "4294967295",
  "time": "2022-09-29T07:36:00.000Z"
}