{
  "subject": "account",
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "118450",
  "datafield1": "uname",
  "datafield2": "root",
  "datafield3": "0755",
  "datafield4": "/usr/bin/uname",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/1",
  "msgid": "execveat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "-a",
  "object.process.cwd": "/root",
  "object.process.fullpath": "/bin/uname",
  "object.process.id": "12680",
  "object.process.meta": "./bin",
  "object.process.name": "uname",
  "object.process.parent.id": "12309",
  "object.process.path": "/bin/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "229",
  "time": "2019-09-10T10:02:31.000Z"
}