{
  "action": "start",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "chain_id": "426440568",
  "datafield1": "check_ifs_vip.p",
  "datafield2": "root",
  "datafield3": "0751",
  "datafield4": "/opt/waf/python/bin/python",
  "event_src.category": "Operating system",
  "event_src.hostname": "linx-web-ptaf-02",
  "event_src.rule": "pt_siem_execve",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_process_start",
  "importance": "low",
  "msgid": "execve",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "/opt/waf/python/bin/python /etc/monit/scripts/check_ifs_vip.py dummy0",
  "object.process.cwd": "/",
  "object.process.fullpath": "/etc/monit/scripts/check_ifs_vip.py",
  "object.process.id": "14985",
  "object.process.meta": "/opt/waf/python/bin/python /etc/monit/scripts/check_ifs_vip.py dummy0",
  "object.process.name": "check_ifs_vip.py",
  "object.process.parent.id": "61591",
  "object.process.path": "/etc/monit/scripts/",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "time": "2022-05-11T16:35:31.000Z"
}