{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "ongoing",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Application",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.xpc.proxy",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_setting_process_group_id",
  "importance": "info",
  "msgid": "104",
  "object.account.id": "0",
  "object.account.session_id": "11290",
  "object.group": "20",
  "object.process.fullpath": "/usr/libexec/xpcproxy",
  "object.process.id": "11290",
  "object.process.name": "xpcproxy",
  "object.process.parent.id": "1",
  "object.process.path": "/usr/libexec/",
  "subject.account.id": "0",
  "subject.account.session_id": "11290",
  "subject.process.fullpath": "/usr/libexec/xpcproxy",
  "subject.process.hash": "UNKNOWN:3CA16C0D5EC85D743A1A9C840E388D08A1615235",
  "subject.process.id": "11290",
  "subject.process.name": "xpcproxy",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T14:50:15.948Z"
}