{
  "subject": "account",
  "action": "access",
  "object": "process",
  "status": "success",
  "chain_id": "9681",
  "datafield1": "strace",
  "event_src.category": "Operating system",
  "event_src.hostname": "pewpew-pc",
  "event_src.rule": "pt_siem_api_ptrace",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_ptrace",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "ptrace",
  "object.account.group": "0",
  "object.account.id": "0",
  "object.process.id": "4574",
  "object.property": "request_info",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "61",
  "subject.process.fullpath": "/usr/bin/strace",
  "subject.process.id": "4572",
  "subject.process.meta": "strace /usr/bin/dirname",
  "subject.process.name": "strace",
  "subject.process.parent.id": "4336",
  "subject.process.path": "/usr/bin/",
  "time": "2019-05-18T20:56:35.000Z"
}