{
  "subject": "account",
  "action": "access",
  "object": "process",
  "status": "success",
  "chain_id": "300",
  "datafield1": "strace",
  "datafield7": "Current process is traced by its parent",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_api_ptrace",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_ptrace",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "ptrace",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.cmdline": "strace --attach=1",
  "object.process.fullpath": "/usr/bin/strace",
  "object.process.id": "3038",
  "object.process.name": "strace",
  "object.process.parent.id": "3036",
  "object.process.path": "/usr/bin/",
  "object.property": "request_info",
  "object.value": "PTRACE_TRACEME",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "0",
  "subject.account.session_id": "3",
  "subject.process.id": "3036",
  "time": "2022-05-19T08:32:49.000Z"
}