{
  "action": "access",
  "object": "process",
  "status": "success",
  "chain_id": "13129159",
  "datafield1": "creds-util",
  "datafield7": "Detach from a traced process",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.123",
  "event_src.rule": "pt_siem_api_ptrace",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_ptrace",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "ptrace",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.id": "8859",
  "object.property": "request_info",
  "object.value": "PTRACE_DETACH",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/home/src/build/bin/suricata/analyzers/http/creds/creds-util",
  "subject.process.id": "15287",
  "subject.process.meta": "./creds-util -O/home/src/build/bin/suricata/analyzers/http/creds/creds.db /home/src/distr/http-creds/http-creds.yaml",
  "subject.process.name": "creds-util",
  "subject.process.parent.id": "15286",
  "subject.process.path": "/home/src/build/bin/suricata/analyzers/http/creds/",
  "time": "2022-05-19T09:52:38.000Z"
}