{
  "action": "access",
  "object": "process",
  "status": "success",
  "chain_id": "13118311",
  "datafield1": "cmTC_0f331",
  "datafield7": "Attach to a process with SIGSTOP sending",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.177.123",
  "event_src.rule": "pt_siem_api_ptrace",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_ptrace",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "ptrace",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.process.id": "6953",
  "object.process.name": "cmTC_0f331",
  "object.property": "request_info",
  "object.value": "PTRACE_ATTACH",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/home/src/build/CMakeFiles/CMakeTmp/cmTC_0f331",
  "subject.process.id": "6954",
  "subject.process.meta": "/home/src/build/CMakeFiles/CMakeTmp/cmTC_0f331",
  "subject.process.name": "cmTC_0f331",
  "subject.process.parent.id": "6953",
  "subject.process.path": "/home/src/build/CMakeFiles/CMakeTmp/",
  "time": "2022-05-19T09:41:13.000Z"
}