{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield10": "f_fssubtype:0|f_bavail: 0|f_fsid: |f_files: 0|f_owner: 0|f_flags_ext: 0|f_blocks: 0|f_bfree: 0|f_ffree: 0",
  "datafield11": "EG7KH642X6",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "false",
  "datafield6": "false",
  "datafield7": "mount_vmhgfs",
  "datafield8": "570490881",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_filesystem_mount",
  "importance": "info",
  "msgid": "22",
  "object.name": "vmhgfs",
  "object.new_value": "/Volumes/VMware Shared Folders",
  "object.property": "mount path",
  "object.type": "30",
  "object.value": ".host:/VMware Shared Folders",
  "subject.account.id": "0",
  "subject.account.session_id": "12622",
  "subject.process.fullpath": "/Library/Application Support/VMware Tools/mount_vmhgfs",
  "subject.process.hash": "UNKNOWN:65CCB73B8F70662CB268B96DE811CDB38D3E44C4",
  "subject.process.id": "12636",
  "subject.process.name": "mount_vmhgfs",
  "subject.process.parent.id": "12623",
  "subject.process.path": "/Library/Application Support/VMware Tools/",
  "time": "2023-07-24T16:47:28.938Z"
}