{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.sshd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_change_root_directory",
  "importance": "info",
  "msgid": "57",
  "object.new_value": "/private/var/empty",
  "subject.account.id": "0",
  "subject.account.session_id": "12527",
  "subject.process.fullpath": "/usr/sbin/sshd",
  "subject.process.hash": "UNKNOWN:7F5C5E50AD1A8C11F4ACFD6331376B9307DC9302",
  "subject.process.id": "12528",
  "subject.process.name": "sshd",
  "subject.process.parent.id": "12527",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-07-24T16:46:45.203Z"
}