{
  "action": "create",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "21300",
  "datafield1": "(fwupd)",
  "event_src.category": "Operating system",
  "event_src.ip": "10.126.12.217",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "mkdir",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.path": "/etc/",
  "object.type": "directory",
  "reason": "File exists",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/lib/systemd/systemd",
  "subject.process.id": "18867",
  "subject.process.meta": "(fwupd)",
  "subject.process.name": "systemd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/lib/systemd/",
  "time": "2022-05-16T08:46:03.000Z"
}