{
  "action": "create",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "4915221",
  "datafield1": "synchrony-inter",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.56.89",
  "event_src.rule": "pt_siem_home_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "mkdir",
  "object.account.group": "confluence",
  "object.account.id": "1007",
  "object.account.name": "confluence",
  "object.fullpath": "/home/confluence",
  "object.name": "confluence",
  "object.path": "/home/",
  "object.type": "directory",
  "reason": "Permission denied",
  "subject.account.id": "1007",
  "subject.account.name": "confluence",
  "subject.account.privileges": "1007",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/opt/atlassian/confluence/bin",
  "subject.process.fullpath": "/opt/atlassian/confluence/jre/bin/java",
  "subject.process.id": "54768",
  "subject.process.meta": "/opt/atlassian/confluence/jre//bin/java -Djava.util.logging.config.file=/opt/atlassian/confluence/conf/logging.properties -Djava",
  "subject.process.name": "java",
  "subject.process.parent.id": "1",
  "subject.process.path": "/opt/atlassian/confluence/jre/bin/",
  "time": "2023-05-13T11:17:33.000Z"
}