{
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "31333343",
  "datafield1": "git-lfs",
  "datafield2": "root",
  "datafield3": "0777",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.176.188",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "mkdirat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/home/gitlab-runner/disk/builds/s9ZwbBxz/0/X/chains/.git/modules/autodeploy/lfs",
  "object.id": "1468616",
  "object.name": "lfs",
  "object.path": "/home/gitlab-runner/disk/builds/s9ZwbBxz/0/X/chains/.git/modules/autodeploy/",
  "object.type": "directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/home/gitlab-runner/disk/builds/s9ZwbBxz/0/X/chains/autodeploy",
  "subject.process.fullpath": "/usr/bin/git-lfs",
  "subject.process.id": "33543",
  "subject.process.meta": "/usr/bin/git-lfs pull",
  "subject.process.name": "git-lfs",
  "subject.process.parent.id": "33540",
  "subject.process.path": "/usr/bin/",
  "time": "2022-09-14T11:17:37.000Z"
}