{
  "subject": "account",
  "action": "create",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "861071",
  "datafield1": "mkdir",
  "datafield2": "root",
  "datafield3": "0755",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/7",
  "msgid": "mkdir",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/toor",
  "object.id": "420272",
  "object.name": "toor",
  "object.path": "/root/",
  "object.type": "directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "11",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/mkdir",
  "subject.process.id": "48046",
  "subject.process.meta": "mkdir toor",
  "subject.process.name": "mkdir",
  "subject.process.parent.id": "3668",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-20T08:25:54.000Z"
}