{
  "subject": "account",
  "action": "remove",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "375466",
  "datafield1": "dpkg",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.rule": "pt_siem_bin_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/5",
  "msgid": "rmdir",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.path": "/usr/bin/",
  "object.type": "directory",
  "reason": "No such file or directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "391",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/bin/dpkg",
  "subject.process.id": "36418",
  "subject.process.meta": "/usr/bin/dpkg --status-fd 20 --no-triggers --unpack --auto-deconfigure /var/cache/apt/archives/vim-runtime_2%3a8.1.0875-5_all.de",
  "subject.process.name": "dpkg",
  "subject.process.parent.id": "36397",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-18T04:03:41.000Z"
}