{
  "action": "create",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "30576769",
  "datafield1": "gitlab-runner-h",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.10.10",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_folder_modify",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "mkdirat",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.path": "/home/gitlab-runner/disk/builds/s9ZwbBxz/0/X/rules/public/",
  "object.type": "directory",
  "reason": "File exists",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/home/gitlab-runner/disk/builds/s9ZwbBxz/0/X/rules",
  "subject.process.fullpath": "/usr/bin/gitlab-runner-helper",
  "subject.process.id": "7931",
  "subject.process.meta": "/usr/bin/gitlab-runner-helper cache-extractor --file ../../../../../cache/X/rules/default-non_protected/cache.zip --timeout 1",
  "subject.process.name": "gitlab-runner-helper",
  "subject.process.parent.id": "7919",
  "subject.process.path": "/usr/bin/",
  "time": "2022-09-14T11:01:04.000Z"
}