{
  "action": "rename",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "658437903",
  "datafield1": "php-fpm7.4",
  "event_src.category": "Operating system",
  "event_src.ip": "192.70.198.184",
  "event_src.rule": "pt_siem_www_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "rename",
  "object.account.group": "www-data",
  "object.account.id": "33",
  "object.account.name": "www-data",
  "object.new_value": "/var/www/www.site.ru/bitrix/cache/css/ru/site_pages/template_ca8d42298605cb0e3b9c69b6bcc15962/",
  "object.path": "/var/www/www.site.ru/bitrix/cache/css/ru/site_pages/template_ca8d42298605cb0e3b9c69b6bcc15962/",
  "object.property": "path",
  "reason": "No such file or directory",
  "subject.account.id": "33",
  "subject.account.name": "www-data",
  "subject.account.privileges": "33",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/var/www/www.site.ru/bitrix",
  "subject.process.fullpath": "/usr/sbin/php-fpm7.4",
  "subject.process.id": "3964043",
  "subject.process.meta": "php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)",
  "subject.process.name": "php-fpm7.4",
  "subject.process.parent.id": "633",
  "subject.process.path": "/usr/sbin/",
  "time": "2022-05-04T09:06:06.000Z"
}