{
  "action": "move",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "33681467",
  "datafield1": "php-fpm7.4",
  "datafield2": "www-data",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.ip": "10.16.20.26",
  "event_src.rule": "pt_siem_www_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "rename",
  "numfield2": 33,
  "object.account.group": "www-data",
  "object.account.id": "33",
  "object.account.name": "www-data",
  "object.fullpath": "/var/www/data/azhukov/files/Памятка про согласование договоров 2.pdf",
  "object.id": "3146669",
  "object.name": "Памятка про согласование договоров 2.pdf",
  "object.new_value": "/var/www/data/azhukov/files_trashbin/files/Памятка про согласование договоров 2.pdf.d1683399688",
  "object.path": "/var/www/data/azhukov/files/",
  "object.property": "fullpath",
  "object.type": "regular_file",
  "subject.account.id": "33",
  "subject.account.name": "www-data",
  "subject.account.privileges": "33",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/var/www",
  "subject.process.fullpath": "/usr/sbin/php-fpm7.4",
  "subject.process.id": "504316",
  "subject.process.meta": "php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)",
  "subject.process.name": "php-fpm7.4",
  "subject.process.parent.id": "568",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-06T19:01:28.000Z"
}