{
  "subject": "account",
  "action": "move",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "3423061",
  "datafield1": "ansible-galaxy",
  "datafield2": "mkislov",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.52.40",
  "event_src.rule": "pt_siem_home_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/12",
  "msgid": "rename",
  "numfield2": 1004,
  "object.account.group": "mkislov",
  "object.account.id": "1004",
  "object.account.name": "mkislov",
  "object.fullpath": "/home/mkislov/.ansible/tmp/ansible-local-325088_ilb_jce/tmpef9u1wwv/tmpfyvq8aq_",
  "object.id": "2001966",
  "object.name": "tmpfyvq8aq_",
  "object.new_value": "/home/mkislov/.ansible/collections/ansible_collections/community/hashi_vault/tests/integration/targets/lookup_vault_read/tasks/lookup_vault_read_setup.yml",
  "object.path": "/home/mkislov/.ansible/tmp/ansible-local-325088_ilb_jce/tmpef9u1wwv/",
  "object.property": "fullpath",
  "object.type": "regular_file",
  "subject.account.id": "1004",
  "subject.account.name": "mkislov",
  "subject.account.privileges": "1004",
  "subject.account.session_id": "357",
  "subject.process.cwd": "/home/mkislov/ansible",
  "subject.process.fullpath": "/usr/bin/python3.9",
  "subject.process.id": "325088",
  "subject.process.meta": "/home/mkislov/ansible_2.14/bin/python /home/mkislov/ansible_2.14/bin/ansible-galaxy collection install community.hashi_vault --f",
  "subject.process.name": "python3.9",
  "subject.process.parent.id": "313439",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-06T13:15:22.000Z"
}