{
  "subject": "account",
  "action": "rename",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "2062163",
  "datafield1": "mv",
  "datafield2": "jr",
  "datafield3": "0775",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.217.72",
  "event_src.rule": "my_test",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/1",
  "msgid": "renameat2",
  "numfield2": 1000,
  "object.account.group": "jr",
  "object.account.id": "1000",
  "object.account.name": "jr",
  "object.id": "1443658",
  "object.path": "/home/jr/tested_dir/../",
  "object.property": "fullpath",
  "object.type": "directory",
  "subject.account.id": "1000",
  "subject.account.name": "jr",
  "subject.account.privileges": "1000",
  "subject.account.session_id": "3",
  "subject.process.cwd": "/home/jr/tested_dir",
  "subject.process.fullpath": "/usr/bin/mv",
  "subject.process.id": "3079",
  "subject.process.meta": "mv ../test_dir_copied/ ./test_backwards/",
  "subject.process.name": "mv",
  "subject.process.parent.id": "3062",
  "subject.process.path": "/usr/bin/",
  "time": "2020-03-31T15:35:10.000Z"
}