{
  "subject": "account",
  "action": "rename",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "374617",
  "datafield1": "mv",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.rule": "pt_siem_boot_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/1",
  "msgid": "renameat2",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/boot/initrd.img-4.19.0-6-amd64.evil2",
  "object.id": "393222",
  "object.name": "initrd.img-4.19.0-6-amd64.evil2",
  "object.new_value": "/boot/initrd.img-4.19.0-6-amd64.evil1",
  "object.path": "/boot/",
  "object.property": "fullpath",
  "object.type": "regular_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "391",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/mv",
  "subject.process.id": "36145",
  "subject.process.meta": "mv -f /boot/initrd.img-4.19.0-6-amd64.evil2 /boot/initrd.img-4.19.0-6-amd64.evil1",
  "subject.process.name": "mv",
  "subject.process.parent.id": "34101",
  "subject.process.path": "/usr/bin/",
  "time": "2019-12-18T03:36:00.000Z"
}