{
  "subject": "account",
  "action": "move",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "27852553",
  "datafield1": "mv",
  "datafield3": "0755",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.52.40",
  "event_src.rule": "pt_siem_rename",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_resource_rename",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/2",
  "msgid": "renameat2",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.id": "262906",
  "object.new_value": "/root/test_dir/test_dir_22",
  "object.path": "/root/test_dir/../",
  "object.property": "fullpath",
  "object.type": "directory",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "9",
  "subject.process.cwd": "/root/test_dir",
  "subject.process.fullpath": "/usr/bin/mv",
  "subject.process.id": "83734",
  "subject.process.meta": "mv ../test_dir_2/ ./test_dir_22",
  "subject.process.name": "mv",
  "subject.process.parent.id": "81455",
  "subject.process.path": "/usr/bin/",
  "time": "2023-05-15T07:00:49.000Z"
}