{
  "subject": "account",
  "action": "modify",
  "object": "user_group",
  "status": "success",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "16411398",
  "event_src.category": "Operating system",
  "event_src.hostname": "treat",
  "event_src.ip": "10.16.20.11",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_del_user",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "DEL_USER",
  "object.property": "removed_user",
  "object.state": "deleting user from shadow group",
  "object.value": "resko",
  "subject.account.id": "1000",
  "subject.account.name": "ansible",
  "subject.account.privileges": "0",
  "subject.account.session_id": "19121",
  "subject.process.fullpath": "/usr/sbin/userdel",
  "subject.process.id": "2182693",
  "subject.process.name": "userdel",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-25T13:18:00.000Z"
}