{
  "subject": "account",
  "action": "stop",
  "object": "process",
  "status": "success",
  "category.generic": "Process",
  "category.high": "Availability Management",
  "category.low": "Control",
  "datafield1": "999",
  "event_src.category": "Operating system",
  "event_src.fqdn": "someone.acme.com",
  "event_src.hostname": "someone",
  "event_src.subsys": "Security",
  "event_src.title": "windows",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_Windows_eventlog_4689_A_process_has_exited",
  "importance": "info",
  "msgid": "4689",
  "object.account.domain": "acme",
  "object.account.id": "S-1-5-18",
  "object.account.name": "someone$",
  "object.account.session_id": "999",
  "object.id": "9280",
  "object.name": "searchfilterhost.exe",
  "object.path": "c:\\windows\\system32\\",
  "object.process.fullpath": "c:\\windows\\system32\\searchfilterhost.exe",
  "object.process.id": "9280",
  "object.process.name": "searchfilterhost.exe",
  "object.process.path": "c:\\windows\\system32\\",
  "object.state": "0x0",
  "reason": "0x0",
  "subject.account.domain": "acme",
  "subject.account.id": "S-1-5-18",
  "subject.account.name": "someone$",
  "subject.account.session_id": "999",
  "subject.domain": "acme",
  "subject.id": "S-1-5-18",
  "subject.name": "someone$",
  "time": "2013-10-23T10:11:57.974Z"
}