{
  "subject": "account",
  "action": "execute",
  "object": "command",
  "status": "success",
  "category.generic": "Command",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "DBCC CHECKDB(N'secret') WITH PHYSICAL_ONLY",
  "datafield2": "WIN-RCMC6R0VHU4",
  "datafield3": "master",
  "datafield4": "DBCC",
  "datafield5": "DB",
  "event_src.category": "Database server",
  "event_src.hostname": "win-rcmc6r0vhu4",
  "event_src.subsys": "Application",
  "event_src.title": "sql_server",
  "event_src.vendor": "microsoft",
  "id": "PT_Microsoft_SQL_Server_eventlog_33205_audit_dbcc_execute",
  "importance": "low",
  "msgid": "33205",
  "object.query": "DBCC CHECKDB(N'secret') WITH PHYSICAL_ONLY",
  "subject.account.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.account.name": "admin",
  "subject.id": "307341b39b77b448b8bbb953d2f56a31",
  "subject.name": "admin",
  "time": "2015-09-22T08:54:35Z"
}