{
  "subject": "account",
  "action": "close",
  "object": "session",
  "status": "success",
  "datafield1": "0",
  "datafield12": "1",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.screensharing.daemon",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_screensharing_detach",
  "importance": "info",
  "msgid": "119",
  "object.type": "shared session",
  "src.ip": "192.168.163.129",
  "subject.account.session_id": "257",
  "subject.process.fullpath": "/System/Library/CoreServices/RemoteManagement/screensharingd.bundle/Contents/MacOS/screensharingd",
  "subject.process.hash": "UNKNOWN:082BDC8EE814C227BF272D53F8192543B9C0DD03",
  "subject.process.id": "2966",
  "subject.process.name": "screensharingd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/System/Library/CoreServices/RemoteManagement/screensharingd.bundle/Contents/MacOS/",
  "time": "2023-07-25T09:06:09.018Z"
}