{
  "subject": "process",
  "action": "modify",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "266",
  "datafield2": "266",
  "datafield3": "4294967295",
  "datafield4": "266",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.timed",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_setting_file_mode",
  "importance": "info",
  "msgid": "29",
  "object.fullpath": "/private/var/db/timed/com.apple.timed.plist",
  "object.name": "com.apple.timed.plist",
  "object.path": "/private/var/db/timed/",
  "object.property": "file mode",
  "object.value": "420",
  "subject.account.id": "266",
  "subject.account.session_id": "120",
  "subject.process.fullpath": "/usr/libexec/timed",
  "subject.process.hash": "UNKNOWN:1F8106E63CCF0629522898159B36E09CC19E64DE",
  "subject.process.id": "120",
  "subject.process.name": "timed",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/libexec/",
  "time": "2023-07-24T12:12:25.487Z"
}