{
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "1754547344",
  "datafield1": "rm",
  "datafield2": "root",
  "datafield3": "0700",
  "event_src.category": "Operating system",
  "event_src.ip": "10.0.10.10",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "unlinkat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/default-1",
  "object.id": "3935365",
  "object.name": "default-1",
  "object.path": "/",
  "object.type": "directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/bin/rm",
  "subject.process.id": "365032",
  "subject.process.meta": "rm -rf /home/gitlab-runner/disk/builds /home/gitlab-runner/disk/cache",
  "subject.process.name": "rm",
  "subject.process.parent.id": "1208",
  "subject.process.path": "/bin/",
  "time": "2022-06-03T12:06:36.000Z"
}