{
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "17421842",
  "datafield1": "Cache2 I/O",
  "datafield2": "user@domain.my",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.192.250",
  "event_src.rule": "pt_siem_home_access",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "unlink",
  "numfield2": 1702640790,
  "object.account.domain": "domain.my",
  "object.account.group": "domain users@domain.my",
  "object.account.id": "1702640790",
  "object.account.name": "user",
  "object.fullpath": "/home/user@domain.my/.cache/mozilla/firefox/h4qichs3.default-esr/cache2/doomed/370630586",
  "object.id": "8268748",
  "object.name": "370630586",
  "object.path": "/home/user@domain.my/.cache/mozilla/firefox/h4qichs3.default-esr/cache2/doomed/",
  "object.type": "regular_file",
  "subject.account.domain": "domain.my",
  "subject.account.id": "1702640790",
  "subject.account.name": "user",
  "subject.account.privileges": "1702640790",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/home/user@domain.my",
  "subject.process.fullpath": "/usr/lib/firefox-esr/firefox-esr",
  "subject.process.id": "515625",
  "subject.process.meta": "/usr/bin/x-www-browser",
  "subject.process.name": "firefox-esr",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/lib/firefox-esr/",
  "time": "2022-06-03T15:43:10.000Z"
}