{
  "subject": "account",
  "action": "remove",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "771989814",
  "datafield1": "vault",
  "event_src.category": "Operating system",
  "event_src.ip": "10.10.52.40",
  "event_src.rule": "pt_siem_home_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/15",
  "msgid": "unlinkat",
  "object.account.group": "dperrote",
  "object.account.id": "1016",
  "object.account.name": "dperrote",
  "object.path": "/home/dperrote/",
  "reason": "No such file or directory",
  "subject.account.id": "1016",
  "subject.account.name": "dperrote",
  "subject.account.privileges": "1016",
  "subject.account.session_id": "9956",
  "subject.process.cwd": "/home/dperrote",
  "subject.process.fullpath": "/usr/local/bin/vault",
  "subject.process.id": "13383",
  "subject.process.meta": "vault login role=user",
  "subject.process.name": "vault",
  "subject.process.parent.id": "13288",
  "subject.process.path": "/usr/local/bin/",
  "time": "2022-05-17T07:28:07.000Z"
}