{
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "11876009",
  "datafield1": "seaf-server",
  "datafield2": "seafile",
  "datafield3": "0600",
  "event_src.category": "Operating system",
  "event_src.ip": "10.19.20.35",
  "event_src.rule": "pt_siem_home_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "unlink",
  "numfield2": 1006,
  "object.account.group": "seafile",
  "object.account.id": "1006",
  "object.account.name": "seafile",
  "object.fullpath": "/home/seafile/seafile-data/tmpfiles/10061452502680260917e41e9f49aac7ed5e942f-5PKJM1",
  "object.id": "10554108",
  "object.name": "10061452502680260917e41e9f49aac7ed5e942f-5PKJM1",
  "object.path": "/home/seafile/seafile-data/tmpfiles/",
  "object.type": "regular_file",
  "subject.account.id": "1006",
  "subject.account.name": "seafile",
  "subject.account.privileges": "1006",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/home/seafile/seafile-pro-server-7.0.19/seafile/bin/seaf-server",
  "subject.process.id": "13710",
  "subject.process.meta": "seaf-server -F /home/seafile/conf -c /home/seafile/ccnet -d /home/seafile/seafile-data -l /home/seafile/logs/seafile.log -P /hom",
  "subject.process.name": "seaf-server",
  "subject.process.parent.id": "13093",
  "subject.process.path": "/home/seafile/seafile-pro-server-7.0.19/seafile/bin/",
  "time": "2022-05-17T08:25:37.000Z"
}