{
  "action": "remove",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "8305171",
  "datafield1": "nano",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "logon_service": "pts/5",
  "msgid": "unlink",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.path": "/etc/ssh/",
  "reason": "No such file or directory",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.cwd": "/usr/bin",
  "subject.process.fullpath": "/usr/bin/nano",
  "subject.process.id": "128275",
  "subject.process.meta": "nano /etc/ssh/sshd_config",
  "subject.process.name": "nano",
  "subject.process.parent.id": "128217",
  "subject.process.path": "/usr/bin/",
  "time": "2022-05-18T07:26:01.000Z"
}