{
  "subject": "account",
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "3924",
  "datafield1": "rm",
  "datafield2": "root",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.ip": "192.168.137.192",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "logon_service": "pts/0",
  "msgid": "unlinkat",
  "numfield2": 0,
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.fullpath": "/root/-rf ",
  "object.id": "421991",
  "object.name": "-rf ",
  "object.path": "/root/",
  "object.type": "regular_file",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "1",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/usr/bin/rm",
  "subject.process.id": "1727",
  "subject.process.meta": "rm ./-rf ",
  "subject.process.name": "rm",
  "subject.process.parent.id": "1707",
  "subject.process.path": "/usr/bin/",
  "time": "2020-02-14T11:37:17.000Z"
}