{
  "subject": "account",
  "action": "remove",
  "object": "file_object",
  "status": "failure",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "124412",
  "datafield1": "rm",
  "event_src.category": "Operating system",
  "event_src.ip": "127.0.0.1",
  "event_src.rule": "pt_siem_etc_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "logon_service": "pts/1",
  "msgid": "unlinkat",
  "object.account.group": "root",
  "object.account.id": "0",
  "object.account.name": "root",
  "object.path": "/etc/rc6.d/",
  "reason": "No such file or directory",
  "subject.account.id": "1000",
  "subject.account.name": "cm",
  "subject.account.privileges": "0",
  "subject.account.session_id": "3545",
  "subject.process.cwd": "/",
  "subject.process.fullpath": "/usr/bin/rm",
  "subject.process.id": "50284",
  "subject.process.meta": "rm -f /etc/rc0.d/K20saslauthd /etc/rc6.d/K20saslauthd",
  "subject.process.name": "rm",
  "subject.process.parent.id": "50270",
  "subject.process.path": "/usr/bin/",
  "time": "2022-05-17T06:44:55.000Z"
}