{
  "subject": "account",
  "action": "remove",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "chain_id": "28758",
  "datafield1": "nano",
  "datafield3": "0644",
  "event_src.category": "Operating system",
  "event_src.hostname": "debian-test",
  "event_src.rule": "pt_siem_cron_modify",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_syscall_link_remove",
  "importance": "low",
  "logon_service": "pts/0",
  "msgid": "unlink",
  "numfield2": 0,
  "object.account.group": "0",
  "object.account.id": "0",
  "object.fullpath": "/var/spool/cron/crontabs/.test.swp",
  "object.id": "264212",
  "object.name": ".test.swp",
  "object.path": "/var/spool/cron/crontabs/",
  "object.type": "regular_file",
  "subject.account.id": "1000",
  "subject.account.privileges": "0",
  "subject.account.session_id": "178",
  "subject.process.cwd": "/root",
  "subject.process.fullpath": "/bin/nano",
  "subject.process.id": "2490",
  "subject.process.meta": "nano /var/spool/cron/crontabs/test",
  "subject.process.name": "nano",
  "subject.process.parent.id": "2445",
  "subject.process.path": "/bin/",
  "time": "2019-04-29T16:47:43.000Z"
}