{
  "action": "create",
  "object": "user_group",
  "status": "ongoing",
  "category.generic": "Group",
  "category.high": "Users And Rights Management",
  "category.low": "Manipulation",
  "chain_id": "61235388",
  "event_src.category": "Operating system",
  "event_src.ip": "10.20.177.128",
  "event_src.subsys": "auditd",
  "event_src.title": "unix_like",
  "id": "PT_UNIX_like_auditd_syslog_structured_grp_mgmt",
  "importance": "low",
  "labels": "node_contains_ext_ip",
  "msgid": "GRP_MGMT",
  "object.id": "90",
  "object.name": "unknown(90)",
  "object.state": "add-shadow-group",
  "subject.account.id": "0",
  "subject.account.name": "root",
  "subject.account.privileges": "0",
  "subject.account.session_id": "4294967295",
  "subject.process.fullpath": "/usr/sbin/groupadd",
  "subject.process.id": "46328",
  "subject.process.name": "groupadd",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-05-06T02:19:13.000Z"
}