{
  "subject": "process",
  "action": "modify",
  "object": "process",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "0",
  "datafield2": "0",
  "datafield3": "4294967295",
  "datafield4": "0",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.bluetoothd",
  "datafield8": "570522385",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_change_directory",
  "importance": "info",
  "msgid": "51",
  "object.new_value": "/private/var/root/Library/Logs/Bluetooth",
  "subject.account.id": "0",
  "subject.account.session_id": "7988",
  "subject.process.fullpath": "/usr/sbin/bluetoothd",
  "subject.process.hash": "UNKNOWN:2EB0BA18CE42611086419421543A9461B3024143",
  "subject.process.id": "7988",
  "subject.process.name": "bluetoothd",
  "subject.process.parent.id": "1",
  "subject.process.path": "/usr/sbin/",
  "time": "2023-07-24T12:12:25.722Z"
}