{
  "subject": "process",
  "action": "copy",
  "object": "file_object",
  "status": "success",
  "category.generic": "File System Object",
  "category.high": "System Management",
  "category.low": "Manipulation",
  "datafield1": "502",
  "datafield12": "1",
  "datafield2": "20",
  "datafield3": "502",
  "datafield4": "20",
  "datafield5": "true",
  "datafield6": "false",
  "datafield7": "com.apple.mv",
  "datafield8": "570506001",
  "event_src.category": "Host security",
  "event_src.title": "edr",
  "event_src.vendor": "positive_technologies",
  "id": "PT_Positive_Technologies_XDR_es_logger_file_renamed",
  "importance": "info",
  "msgid": "25",
  "object.fullpath": "/Users/vsamal/Work/1.txt",
  "object.name": "1.txt",
  "object.new_value": "/Users/vsamal/Work/3.txt",
  "object.path": "/Users/vsamal/Work/",
  "object.property": "new fullpath",
  "subject.account.id": "502",
  "subject.account.session_id": "2235",
  "subject.process.fullpath": "/bin/mv",
  "subject.process.hash": "UNKNOWN:82B47E579083855C2F0AE366D8FE337D2DA7122D",
  "subject.process.id": "2825",
  "subject.process.name": "mv",
  "subject.process.parent.id": "2235",
  "subject.process.path": "/bin/",
  "time": "2023-10-11T06:03:43.277Z"
}